const level5Words = [];

const level4Words = [];

const level3Words = [];

const level2_lowWords = [];

const level2_low2Words = [];

const level2Words = [
{"word": "account", "meaning": "銀行口座", "page": 21},
{"word": "as a matter of fact", "meaning": "実際のところ", "page": 21},
{"word": "commodity", "meaning": "商品", "page": 21},
{"word": "grace", "meaning": "恵み", "page": 21},
{"word": "distort", "meaning": "歪める", "page": 21},
{"word": "Arctic", "meaning": "北極地方", "page": 21},
{"word": "obsession", "meaning": "強迫観念", "page": 21},
{"word": "obey", "meaning": "従う", "page": 21},
{"word": "rule out", "meaning": "除外する", "page": 21},
{"word": "manipulate", "meaning": "操る", "page": 21},
{"word": "sue", "meaning": "訴える", "page": 21},
{"word": "get rid of", "meaning": "取り除く", "page": 21},
{"word": "Buddhist", "meaning": "仏教", "page": 21},
{"word": "as far as I know", "meaning": "私の知る限り", "page": 21},
{"word": "put off", "meaning": "延期する", "page": 21},
{"word": "extract", "meaning": "抜き取る", "page": 21},
{"word": "as if", "meaning": "まるで～かのように", "page": 21},
{"word": "indigenous", "meaning": "原産の", "page": 21}
{"word": "slavery", "meaning": "奴隷制度", "page": 21},
{"word": "avenue", "meaning": "大通り", "page": 21},
{"word": "destination", "meaning": "目的地，行き先", "page": 21},
{"word": "designate", "meaning": "選定する", "page": 21},
{"word": "domain", "meaning": "領地", "page": 21},
{"word": "result in", "meaning": "結果として，結果～になる", "page": 21},
{"word": "infrastructure", "meaning": "基盤", "page": 21},
{"word": "provoke", "meaning": "挑発する", "page": 21},
{"word": "sole", "meaning": "単独の", "page": 21},
{"word": "convict", "meaning": "有罪とする", "page": 21},
{"word": "apply for", "meaning": "を申し込む", "page": 21},
{"word": "fatigue", "meaning": "疲労", "page": 21},
{"word": "precede", "meaning": "先行する", "page": 21},
{"word": "decent", "meaning": "まともな", "page": 21},
{"word": "utter", "meaning": "完全な", "page": 21},
{"word": "look over", "meaning": "見渡す", "page": 21},
{"word": "stern", "meaning": "厳格な", "page": 21},
{"word": "breed", "meaning": "を飼育する，繁殖する", "page": 21},
{"word": "no longer", "meaning": "もはや～でない", "page": 21},
{"word": "provided that", "meaning": "と言う条件で", "page": 21},
{"word": "forecast", "meaning": "予測する", "page": 21},
{"word": "evidence", "meaning": "証拠", "page": 21},
{"word": "otherwise", "meaning": "さもなければ", "page": 21},
{"word": "require", "meaning": "を必要とする，を要求する", "page": 21},
{"word": "architect", "meaning": "建築家", "page": 21},
{"word": "lessen", "meaning": "減らす", "page": 21},
{"word": "tumor", "meaning": "腫瘍", "page": 21},
{"word": "dormitory", "meaning": "寮，大部屋", "page": 21},
{"word": "suffer from", "meaning": "で苦しむ，悩まされる", "page": 21},
{"word": "thrust", "meaning": "突き上げる", "page": 21},
{"word": "handout", "meaning": "配布物", "page": 21},
{"word": "addicted", "meaning": "癖になった", "page": 21},
{"word": "kindergarten", "meaning": "幼稚園", "page": 21},
{"word": "reasonable", "meaning": "理性のある，分別のある", "page": 21},
{"word": "phenomenon", "meaning": "現象", "page": 21},
{"word": "accommodate", "meaning": "収容する", "page": 21},
{"word": "obscure", "meaning": "不明瞭な", "page": 21},
{"word": "aisle", "meaning": "通路", "page": 21},
{"word": "resign", "meaning": "辞任する", "page": 21},
{"word": "due to", "meaning": "が原因で", "page": 21},
{"word": "grocery", "meaning": "食料品", "page": 21},
{"word": "toll", "meaning": "料金", "page": 21},
{"word": "transaction", "meaning": "取引", "page": 21},
{"word": "stiff", "meaning": "硬い", "page": 21},
{"word": "put up with", "meaning": "に耐える", "page": 21},
{"word": "deal with", "meaning": "に対処する", "page": 21},
{"word": "induce", "meaning": "誘発する", "page": 21},
{"word": "withstand", "meaning": "耐える", "page": 21},
{"word": "sanitation", "meaning": "衛生", "page": 21},
{"word": "fraction", "meaning": "分数", "page": 21},
{"word": "conceal", "meaning": "隠す", "page": 21},
{"word": "retail", "meaning": "小売り", "page": 21},
{"word": "isolation", "meaning": "隔離", "page": 21},
{"word": "before long", "meaning": "間もなく", "page": 21},
{"word": "biology", "meaning": "生物学", "page": 21},
{"word": "in terms of", "meaning": "に関して，の点から", "page": 21},
{"word": "by the end of", "meaning": "の終わりまでに", "page": 21},
{"word": "prejudice", "meaning": "先入観", "page": 21},
{"word": "souvenir", "meaning": "お土産", "page": 21},
{"word": "bring up", "meaning": "持ち出す", "page": 21},
{"word": "supervisor", "meaning": "上司", "page": 21},
{"word": "struggle", "meaning": "もがき苦しむ", "page": 21},
{"word": "attribute", "meaning": "に帰する", "page": 21},
{"word": "subsequent", "meaning": "その後の", "page": 21},
{"word": "soak", "meaning": "浸す", "page": 21},
{"word": "supplement", "meaning": "補足，追加", "page": 21},
{"word": "drought", "meaning": "干ばつ", "page": 21},
{"word": "rely on", "meaning": "に頼る，を当てにする", "page": 21},
{"word": "penetrate", "meaning": "貫く", "page": 21},
{"word": "conform", "meaning": "従う", "page": 21},
{"word": "at most", "meaning": "多くとも，せいぜい", "page": 21},
{"word": "scarce", "meaning": "乏しい", "page": 21},
{"word": "trivial", "meaning": "取るに足らない", "page": 21},
{"word": "thorough", "meaning": "徹底した", "page": 21},
{"word": "urge", "meaning": "強く促す，早める", "page": 21},
{"word": "predator", "meaning": "捕食者", "page": 21},
{"word": "beverage", "meaning": "飲料", "page": 21},
{"word": "emperor", "meaning": "皇帝，天皇", "page": 21},
{"word": "soar", "meaning": "舞い上がる", "page": 21},
{"word": "embarrassed", "meaning": "恥ずかしい", "page": 21},
{"word": "and so on", "meaning": "などなど", "page": 21},
{"word": "famine", "meaning": "食料不足", "page": 21},
{"word": "secondhand", "meaning": "中古の", "page": 22},
{"word": "bureau", "meaning": "事務局，たんす", "page": 22},
{"word": "extinct", "meaning": "絶滅した", "page": 22},
{"word": "on duty", "meaning": "勤務時間中で，当番の", "page": 22},
{"word": "roast", "meaning": "あぶり焼きにする", "page": 22},
{"word": "along with", "meaning": "に沿って", "page": 22},
{"word": "make fun of", "meaning": "をからかう", "page": 22},
{"word": "conquer", "meaning": "征服する", "page": 22},
{"word": "come up with", "meaning": "を思いつく，を考え出す", "page": 22},
{"word": "converse", "meaning": "逆の", "page": 22},
{"word": "revise", "meaning": "改訂する", "page": 22},
{"word": "lawyer", "meaning": "弁護士，法律家", "page": 22},
{"word": "dip", "meaning": "少し浸す", "page": 22},
{"word": "look into", "meaning": "を調べる", "page": 22},
{"word": "optimistic", "meaning": "楽観的な", "page": 22},
{"word": "neat", "meaning": "きちんとした", "page": 22},
{"word": "refer", "meaning": "言及する", "page": 22},
{"word": "expire", "meaning": "期限切れの", "page": 22},
{"word": "imperial", "meaning": "帝国の", "page": 22},
{"word": "hierarchy", "meaning": "階層", "page": 22},
{"word": "erosion", "meaning": "侵食", "page": 22},
{"word": "evoke", "meaning": "呼び起こす", "page": 22},
{"word": "chemistry", "meaning": "化学", "page": 22},
{"word": "habit", "meaning": "習慣，慣習", "page": 22},
{"word": "vanish", "meaning": "消える", "page": 22},
{"word": "medieval", "meaning": "中世の", "page": 22},
{"word": "earnest", "meaning": "真剣な", "page": 22},
{"word": "get by", "meaning": "どうにか切り抜ける", "page": 22},
{"word": "cope with", "meaning": "に対処する", "page": 22},
{"word": "savage", "meaning": "獰猛な", "page": 22},
{"word": "spur", "meaning": "刺激", "page": 22},
{"word": "bleed", "meaning": "出血する", "page": 22},
{"word": "eyesight", "meaning": "視界", "page": 22},
{"word": "apologize", "meaning": "謝る，謝罪する", "page": 22},
{"word": "concentrate", "meaning": "集中する", "page": 22},
{"word": "utilize", "meaning": "利用する", "page": 22},
{"word": "fame", "meaning": "名声", "page": 22},
{"word": "accommodation", "meaning": "宿泊施設", "page": 22},
{"word": "donate", "meaning": "を寄付する，を寄贈する", "page": 22},
{"word": "starve", "meaning": "飢える", "page": 22},
{"word": "in spite of", "meaning": "にも関わらず", "page": 22},
{"word": "organ", "meaning": "臓器", "page": 22},
{"word": "domestic", "meaning": "国内の，自国の", "page": 22},
{"word": "discrimination", "meaning": "差別/差別的な", "page": 22},
{"word": "bully", "meaning": "いじめっ子", "page": 22},
{"word": "bake", "meaning": "焼く，焼成する", "page": 22},
{"word": "ambiguous", "meaning": "あいまいな", "page": 22},
{"word": "integrate", "meaning": "統合する", "page": 22},
{"word": "particle", "meaning": "分子", "page": 22},
{"word": "magnificent", "meaning": "壮大な", "page": 22},
{"word": "pastime", "meaning": "娯楽", "page": 22},
{"word": "enrich", "meaning": "豊かにする", "page": 22},
{"word": "refund", "meaning": "払い戻す", "page": 22},
{"word": "germ", "meaning": "細菌", "page": 22},
{"word": "rumor", "meaning": "うわさ", "page": 22},
{"word": "run out of", "meaning": "を使い果たす，消耗する", "page": 22},
{"word": "descend", "meaning": "下降する", "page": 22},
{"word": "irrelevant", "meaning": "無関係な", "page": 22},
{"word": "endow", "meaning": "寄付する", "page": 22},
{"word": "fingerprint", "meaning": "指紋", "page": 22},
{"word": "vending machine", "meaning": "自動販売機", "page": 22},
{"word": "compile", "meaning": "編集する", "page": 22},
{"word": "compassion", "meaning": "思いやり", "page": 22},
{"word": "ancestor", "meaning": "祖先，先祖", "page": 22},
{"word": "in case", "meaning": "万一に備えて", "page": 22},
{"word": "think over", "meaning": "熟考する，よく考える", "page": 22},
{"word": "according to", "meaning": "によれば，に基づいて", "page": 22},
{"word": "by degrees", "meaning": "徐々に", "page": 22},
{"word": "sorrow", "meaning": "悲しみ", "page": 22},
{"word": "approve", "meaning": "承認する", "page": 22},
{"word": "undertake", "meaning": "引き受ける", "page": 22},
{"word": "compliment", "meaning": "褒め言葉", "page": 22},
{"word": "hang up", "meaning": "中断する", "page": 22},
{"word": "overwhelm", "meaning": "圧倒する", "page": 22},
{"word": "confess", "meaning": "を打ち明ける，白状する", "page": 22},
{"word": "break out", "meaning": "勃発する", "page": 22},
{"word": "watch out", "meaning": "気を付ける", "page": 22},
{"word": "pull off", "meaning": "もぎ取る，成功を掴む", "page": 22},
{"word": "awkward", "meaning": "ぎこちない", "page": 22},
{"word": "tame", "meaning": "飼いならす", "page": 22},
{"word": "appropriate", "meaning": "適当な，充当する", "page": 22},
{"word": "try on", "meaning": "試着する", "page": 22},
{"word": "adolescent", "meaning": "思春期の", "page": 22},
{"word": "carry out", "meaning": "を成し遂げる", "page": 22},
{"word": "ambition", "meaning": "野望", "page": 22},
{"word": "scholarship", "meaning": "奨学金", "page": 22},
{"word": "get along with", "meaning": "とうまくやっていく", "page": 22},
{"word": "come across", "meaning": "を横切る，出くわす", "page": 22},
{"word": "remain", "meaning": "のままである，残る", "page": 22},
{"word": "out of breath", "meaning": "息切れして", "page": 22},
{"word": "emergency", "meaning": "緊急事態，緊急", "page": 22},
{"word": "spouse", "meaning": "配偶者", "page": 22},
{"word": "call off", "meaning": "を中止する", "page": 22},
{"word": "be willing to", "meaning": "する気のある", "page": 22},
{"word": "shrink", "meaning": "縮小する", "page": 22},
{"word": "molecule", "meaning": "分子", "page": 22},
{"word": "document", "meaning": "書類", "page": 22},
{"word": "nap", "meaning": "昼寝", "page": 22},
{"word": "instead of", "meaning": "のかわりに", "page": 22},
{"word": "assemble", "meaning": "組み立てる", "page": 22},
{"word": "injection", "meaning": "注射，注入", "page": 23},
{"word": "endanger", "meaning": "危険にさらす", "page": 23},
{"word": "basin", "meaning": "盆地", "page": 23},
{"word": "suspend", "meaning": "つるす", "page": 23},
{"word": "stem", "meaning": "幹", "page": 23},
{"word": "hand in", "meaning": "を提出する", "page": 23},
{"word": "be engaged in", "meaning": "に従事している", "page": 23},
{"word": "burden", "meaning": "負担，重荷", "page": 23},
{"word": "a couple of", "meaning": "少数の", "page": 23},
{"word": "be well of", "meaning": "元気で", "page": 23},
{"word": "outcome", "meaning": "結果", "page": 23},
{"word": "retrieve", "meaning": "取り戻す", "page": 23},
{"word": "in shape", "meaning": "健康に", "page": 23},
{"word": "make sense", "meaning": "意味をなす", "page": 23},
{"word": "tidy", "meaning": "きちんとした", "page": 23},
{"word": "reveal", "meaning": "明らかにする", "page": 23},
{"word": "consist of", "meaning": "から成り立っている", "page": 23},
{"word": "afterwards", "meaning": "その後", "page": 23},
{"word": "even if", "meaning": "たとえ～だとしても，仮に～であっても", "page": 23},
{"word": "sewage", "meaning": "下水", "page": 23},
{"word": "abolish", "meaning": "廃止する", "page": 23},
{"word": "ugly", "meaning": "醜い", "page": 23},
{"word": "get over", "meaning": "を乗りこえる，克服する", "page": 23},
{"word": "modest", "meaning": "控えめな", "page": 23},
{"word": "bloom", "meaning": "咲く", "page": 23},
{"word": "holy", "meaning": "神聖な，聖なる", "page": 23},
{"word": "assign", "割り当てる", "page": 23},
{"word": "architecture", "meaning": "建築", "page": 23},
{"word": "sparkle", "meaning": "閃光", "page": 23},
{"word": "How come", "meaning": "どうして～", "page": 23},
{"word": "at times", "meaning": "時々", "page": 23},
{"word": "fragment", "meaning": "断片", "page": 23},
{"word": "fare", "meaning": "運賃", "page": 23},
{"word": "prey", "meaning": "獲物", "page": 23},
{"word": "devastate", "meaning": "荒廃させる", "page": 23},
{"word": "show up", "meaning": "現れる", "page": 23},
{"word": "in contrast to", "meaning": "とは対照的に", "page": 23},
{"word": "nutrition", "meaning": "栄養，栄養素", "page": 23},
{"word": "low-income", "meaning": "低収入の", "page": 23},
{"word": "leak", "meaning": "漏れる", "page": 23},
{"word": "exert", "meaning": "行使する", "page": 23},
{"word": "protocol", "meaning": "儀礼", "page": 23},
{"word": "toxic", "meaning": "有毒な", "page": 23},
{"word": "documentary", "meaning": "事実を記録した", "page": 23},
{"word": "acute", "meaning": "鋭角の", "page": 23},
{"word": "prohibit", "meaning": "禁じる", "page": 23},
{"word": "equality", "meaning": "平等さ", "page": 23},
{"word": "organic", "meaning": "無農薬の", "page": 23},
{"word": "formula", "meaning": "式", "page": 23},
{"word": "exclusive", "meaning": "閉鎖的な", "page": 23},
{"word": "sincere", "meaning": "誠実な", "page": 23},
{"word": "vow", "meaning": "誓い", "page": 23},
{"word": "in charge of", "meaning": "の担当をして", "page": 23},
{"word": "intuition", "meaning": "直感", "page": 23},
{"word": "laptop", "meaning": "ノートパソコン", "page": 23},
{"word": "outstanding", "meaning": "並外れた，目立った", "page": 23},
{"word": "tissue", "meaning": "細胞組織，薄い織物", "page": 23},
{"word": "by means of", "meaning": "によって，を用いて", "page": 23},
{"word": "layer", "meaning": "層", "page": 23},
{"word": "sit up", "meaning": "まっすぐ座る", "page": 23},
{"word": "explode", "meaning": "爆発する，破裂する，激増する", "page": 23},
{"word": "irrigation", "meaning": "灌漑", "page": 23},
{"word": "refrain from", "meaning": "を控える，を遠慮する", "page": 23},
{"word": "a bunch of", "meaning": "たくさんの，多量の", "page": 23},
{"word": "altitude", "meaning": "高度", "page": 23},
{"word": "humid", "meaning": "湿っぽい、湿度の高い", "page": 23},
{"word": "hemisphere", "meaning": "半球", "page": 23},
{"word": "salty", "meaning": "塩辛い", "page": 23},
{"word": "custom", "meaning": "習慣，慣習", "page": 23},
{"word": "award", "meaning": "賞", "page": 23},
{"word": "billion", "meaning": "10億", "page": 23},
{"word": "ashamed", "meaning": "恥じて，恥ずかしくて", "page": 23},
{"word": "definitely", "meaning": "もちろん，確かに", "page": 23},
{"word": "do away with", "meaning": "廃止する", "page": 23},
{"word": "litter", "meaning": "ごみ", "page": 23},
{"word": "stare at", "meaning": "をじっと見つめる", "page": 23},
{"word": "invade", "meaning": "侵略する", "page": 23},
{"word": "beat", "meaning": "打ち負かす", "page": 23},
{"word": "stubborn", "meaning": "頑固な", "page": 23},
{"word": "settle down", "meaning": "定住する", "page": 23},
{"word": "harsh", "meaning": "厳しい", "page": 23},
{"word": "prolong", "meaning": "延長する", "page": 23},
{"word": "humble", "meaning": "謙虚な", "page": 23},
{"word": "reinforce", "meaning": "強化する", "page": 23},
{"word": "fragile", "meaning": "もろい", "page": 23},
{"word": "refuge", "meaning": "避難", "page": 23},
{"word": "cut down", "meaning": "を減らす，削減する", "page": 23},
{"word": "bold", "meaning": "勇敢な", "page": 23},
{"word": "breeze", "meaning": "そよ風", "page": 23},
{"word": "lately", "meaning": "最近", "page": 23},
{"word": "tuition", "meaning": "授業料，学費", "page": 23},
{"word": "indicate", "meaning": "指し示す", "page": 23},
{"word": "vivid", "meaning": "鮮やかな", "page": 23},
{"word": "out of stock", "meaning": "在庫切れ", "page": 23},
{"word": "comprehend", "meaning": "理解する", "page": 23},
{"word": "accumulate", "meaning": "蓄積する", "page": 23},
{"word": "summon", "meaning": "召喚する", "page": 23},
{"word": "acquire", "meaning": "を身につける", "page": 23},
{"word": "pedestrian", "meaning": "歩行者", "page": 23},
{"word": "restrain", "meaning": "抑える", "page": 23}
];
const level1_lowWords = [
];
const level1Words = [
];
