const level5Words = [
{"word": "one", "meaning": "一つの", "page": 1},
{"word": "the", "meaning": "その", "page": 1},
{"word": "you", "meaning": "あなたは", "page": 1},
{"word": "my", "meaning": "私の", "page": 1},
{"word": "father", "meaning": "父親", "page": 1},
{"word": "do", "meaning": "する", "page": 1},
{"word": "your", "meaning": "あなたの", "page": 1},
{"word": "in", "meaning": "の中に", "page": 1},
{"word": "read", "meaning": "読む", "page": 1},
{"word": "he", "meaning": "彼は", "page": 1},
{"word": "see", "meaning": "見る", "page": 1},
{"word": "it", "meaning": "それは", "page": 1},
{"word": "mother", "meaning": "母", "page": 1},
{"word": "name", "meaning": "名前", "page": 1},
{"word": "like", "meaning": "好む", "page": 1},
{"word": "how", "meaning": "どのぐらい", "page": 1},
{"word": "school", "meaning": "学校", "page": 1},
{"word": "January", "meaning": "1月", "page": 1},
{"word": "all", "meaning": "全部、全員、全て、みな", "page": 1},
{"word": "old", "meaning": "古い", "page": 1},
{"word": "fruit", "meaning": "果物", "page": 1},
{"word": "speak", "meaning": "話す", "page": 1},
{"word": "where", "meaning": "どこに", "page": 1},
{"word": "long", "meaning": "長い", "page": 1},
{"word": "study", "meaning": "勉強する", "page": 1},
{"word": "chair", "meaning": "椅子", "page": 1},
{"word": "very", "meaning": "非常に", "page": 1},
{"word": "I", "meaning": "私は", "page": 1},
{"word": "our", "meaning": "私たちの", "page": 1},
{"word": "year", "meaning": "年", "page": 1},
{"word": "when", "meaning": "～するとき", "page": 1},
{"word": "a lot of", "meaning": "たくさんの", "page": 1},
{"word": "nice", "meaning": "良い", "page": 1},
{"word": "sing", "meaning": "歌う", "page": 1},
{"word": "fine", "meaning": "元気な、晴れた", "page": 1},
{"word": "right", "meaning": "右に", "page": 1},
{"word": "want", "meaning": "欲しい", "page": 1},
{"word": "red", "meaning": "赤い", "page": 1},
{"word": "much", "meaning": "たくさん", "page": 1},
{"word": "here", "meaning": "ここに", "page": 1},
{"word": "July", "meaning": "7月", "page": 1},
{"word": "cold", "meaning": "冷たい", "page": 1},
{"word": "write", "meaning": "書く、手紙を書く", "page": 1},
{"word": "station", "meaning": "駅", "page": 1},
{"word": "color", "meaning": "色", "page": 1},
{"word": "this", "meaning": "この", "page": 1},
{"word": "she", "meaning": "彼女は", "page": 1},
{"word": "look", "meaning": "見る", "page": 1},
{"word": "many", "meaning": "多くの", "page": 1},
{"word": "two", "meaning": "2", "page": 1},
{"word": "teacher", "meaning": "先生", "page": 1},
{"word": "morning", "meaning": "朝", "page": 1},
{"word": "use", "meaning": "使う", "page": 1},
{"word": "run", "meaning": "を主催する", "page": 1},
{"word": "hungry", "meaning": "空腹の", "page": 1},
{"word": "fish", "meaning": "魚", "page": 1},
{"word": "lunch", "meaning": "昼食", "page": 1},
{"word": "have", "meaning": "持っている", "page": 1},
{"word": "eat", "meaning": "食べる", "page": 1},
{"word": "know", "meaning": "知っている", "page": 1},
{"word": "usually", "meaning": "普通は", "page": 1},
{"word": "season", "meaning": "季節", "page": 1},
{"word": "book", "meaning": "本", "page": 1},
{"word": "winter", "meaning": "冬", "page": 1},
{"word": "stop", "meaning": "止める", "page": 1},
{"word": "three", "meaning": "3", "page": 1},
{"word": "pencil", "meaning": "鉛筆", "page": 1},
{"word": "please", "meaning": "喜ばせる", "page": 1},
{"word": "wall", "meaning": "壁", "page": 1},
{"word": "meet", "meaning": "会う", "page": 1},
{"word": "May", "meaning": "5月", "page": 1},
{"word": "ride", "meaning": "乗る", "page": 1},
{"word": "six", "meaning": "6", "page": 1},
{"word": "always", "meaning": "いつも", "page": 1},
{"word": "drink", "meaning": "飲む", "page": 1},
{"word": "four", "meaning": "4", "page": 1},
{"word": "sister", "meaning": "姉妹", "page": 1},
{"word": "hospital", "meaning": "病院", "page": 1},
{"word": "park", "meaning": "公園", "page": 1},
{"word": "baseball", "meaning": "野球", "page": 1},
{"word": "wash", "meaning": "洗う", "page": 2},
{"word": "cake", "meaning": "ケーキ", "page": 2},
{"word": "bag", "meaning": "カバン", "page": 2},
{"word": "Tuesday", "meaning": "火曜日", "page": 2},
{"word": "try", "meaning": "試す", "page": 2},
{"word": "cook", "meaning": "料理する", "page": 2},
{"word": "watch", "meaning": "見る", "page": 2},
{"word": "nurse", "meaning": "看護師", "page": 2},
{"word": "five", "meaning": "5", "page": 2},
{"word": "seventeen", "meaning": "17", "page": 2},
{"word": "table", "meaning": "机", "page": 2},
{"word": "place", "meaning": "場所", "page": 2},
{"word": "cup", "meaning": "カップ", "page": 2},
{"word": "green", "meaning": "緑", "page": 2},
{"word": "we", "meaning": "私たちは", "page": 2},
{"word": "fifty", "meaning": "50", "page": 2},
{"word": "eleven", "meaning": "11", "page": 2},
{"word": "picture", "meaning": "絵、写真", "page": 2},
{"word": "happy", "meaning": "幸福な", "page": 2},
{"word": "Thursday", "meaning": "木曜日", "page": 2},
{"word": "Japan", "meaning": "日本", "page": 2},
{"word": "hot", "meaning": "暑い", "page": 2},
{"word": "leave", "meaning": "去る，残す，置いて行く", "page": 2},
{"word": "garbage", "meaning": "ゴミ", "page": 2},
{"word": "hand", "meaning": "手", "page": 2},
{"word": "thirty", "meaning": "30", "page": 2},
{"word": "dinner", "meaning": "夕食", "page": 2},
{"word": "Saturday", "meaning": "土曜日", "page": 2},
{"word": "thirteen", "meaning": "13", "page": 2},
{"word": "fourteen", "meaning": "14", "page": 2},
{"word": "sorry", "meaning": "ごめんなさい", "page": 2},
{"word": "large", "meaning": "大きい、広い", "page": 2},
{"word": "enjoy", "meaning": "楽しむ", "page": 2},
{"word": "flower", "meaning": "花", "page": 2},
{"word": "nineteen", "meaning": "19", "page": 2},
{"word": "night", "meaning": "夜", "page": 2},
{"word": "sheep", "meaning": "ヒツジ", "page": 2},
{"word": "car", "meaning": "自動車", "page": 2},
{"word": "library", "meaning": "図書館", "page": 2},
{"word": "March", "meaning": "3月", "page": 2},
{"word": "again", "meaning": "もう一度、再び、また", "page": 2},
{"word": "beautiful", "meaning": "美しい", "page": 2},
{"word": "Friday", "meaning": "金曜日", "page": 2},
{"word": "cool", "meaning": "かっこいい", "page": 2},
{"word": "day", "meaning": "日", "page": 2},
{"word": "October", "meaning": "10月", "page": 2},
{"word": "get", "meaning": "得る", "page": 2},
{"word": "map", "meaning": "地図", "page": 2},
{"word": "family", "meaning": "家族", "page": 2},
{"word": "boy", "meaning": "少年", "page": 2},
{"word": "white", "meaning": "白", "page": 2},
{"word": "house", "meaning": "家", "page": 2},
{"word": "Monday", "meaning": "月曜日", "page": 2},
{"word": "country", "meaning": "国", "page": 2},
{"word": "box", "meaning": "箱", "page": 2},
{"word": "bread", "meaning": "パン", "page": 2},
{"word": "sixteen", "meaning": "16", "page": 2},
{"word": "eighteen", "meaning": "18", "page": 2},
{"word": "put", "meaning": "置く", "page": 2},
{"word": "month", "meaning": "月", "page": 2},
{"word": "cap", "meaning": "帽子", "page": 2},
{"word": "fast", "meaning": "速い", "page": 2},
{"word": "April", "meaning": "4月", "page": 2},
{"word": "autumn", "meaning": "秋", "page": 2},
{"word": "buy", "meaning": "買う", "page": 2},
{"word": "swim", "meaning": "泳ぐ", "page": 2},
{"word": "city", "meaning": "市", "page": 2},
{"word": "room", "meaning": "部屋", "page": 2},
{"word": "brother", "meaning": "兄弟", "page": 2},
{"word": "walk", "meaning": "散歩", "page": 2},
{"word": "August", "meaning": "8月", "page": 2},
{"word": "summer", "meaning": "夏", "page": 2},
{"word": "blue", "meaning": "青い", "page": 2},
{"word": "dog", "meaning": "イヌ", "page": 2},
{"word": "ten", "meaning": "10", "page": 2},
{"word": "eighty", "meaning": "80", "page": 2},
{"word": "doctor", "meaning": "医者", "page": 2},
{"word": "friend", "meaning": "友達", "page": 2},
{"word": "sleep", "meaning": "眠る", "page": 2},
{"word": "busy", "meaning": "忙しい", "page": 2},
{"word": "play", "meaning": "劇", "page": 3},
{"word": "help", "meaning": "助ける", "page": 3},
{"word": "live", "meaning": "住む", "page": 3},
{"word": "February", "meaning": "2月", "page": 3},
{"word": "not", "meaning": "～でない", "page": 3},
{"word": "way", "meaning": "道、方法", "page": 3},
{"word": "fifteen", "meaning": "15", "page": 3},
{"word": "stand", "meaning": "を我慢する", "page": 3},
{"word": "small", "meaning": "小さい", "page": 3},
{"word": "easy", "meaning": "簡単な", "page": 3},
{"word": "bird", "meaning": "鳥", "page": 3},
{"word": "time", "meaning": "時、～回", "page": 3},
{"word": "welcome", "meaning": "歓迎する", "page": 3},
{"word": "best", "meaning": "一番良い", "page": 3},
{"word": "homework", "meaning": "宿題", "page": 3},
{"word": "November", "meaning": "11月", "page": 3},
{"word": "December", "meaning": "12月", "page": 3},
{"word": "Wednesday", "meaning": "水曜日", "page": 3},
{"word": "June", "meaning": "6月", "page": 3},
{"word": "together", "meaning": "一緒に", "page": 3},
{"word": "tree", "meaning": "木", "page": 3},
{"word": "black", "meaning": "黒い", "page": 3},
{"word": "cow", "meaning": "ウシ", "page": 3},
{"word": "Sunday", "meaning": "日曜日", "page": 3},
{"word": "yellow", "meaning": "黄色", "page": 3},
{"word": "spring", "meaning": "春", "page": 3},
{"word": "make", "meaning": "作る、～を～にするする", "page": 3},
{"word": "desk", "meaning": "机", "page": 3},
{"word": "science", "meaning": "科学", "page": 3},
{"word": "sixty", "meaning": "60", "page": 3},
{"word": "twelve", "meaning": "12", "page": 3},
{"word": "cat", "meaning": "猫", "page": 3},
{"word": "window", "meaning": "窓", "page": 3},
{"word": "subject", "meaning": "科目、題目", "page": 3},
{"word": "me", "meaning": "私を(に)", "page": 3},
{"word": "town", "meaning": "街", "page": 3},
{"word": "that", "meaning": "あれ", "page": 3},
{"word": "seven", "meaning": "7", "page": 3},
{"word": "afternoon", "meaning": "午後", "page": 3},
{"word": "why", "meaning": "なぜ", "page": 3},
{"word": "nine", "meaning": "9", "page": 3},
{"word": "girl", "meaning": "少女", "page": 3},
{"word": "up", "meaning": "上へ", "page": 3},
{"word": "too", "meaning": "～もまた", "page": 3},
{"word": "new", "meaning": "新しい", "page": 3},
{"word": "player", "meaning": "選手", "page": 3},
{"word": "seventy", "meaning": "70", "page": 3},
{"word": "egg", "meaning": "卵", "page": 3},
{"word": "ninety", "meaning": "90", "page": 3},
{"word": "forty", "meaning": "40", "page": 3},
{"word": "good", "meaning": "良い", "page": 3},
{"word": "twenty", "meaning": "20", "page": 3},
{"word": "breakfast", "meaning": "朝食", "page": 3},
{"word": "everyone", "meaning": "みんな", "page": 3},
{"word": "number", "meaning": "数", "page": 3},
{"word": "famous", "meaning": "有名な", "page": 3},
{"word": "short", "meaning": "短い", "page": 3},
{"word": "sad", "meaning": "悲しい", "page": 3},
{"word": "is", "meaning": "ある、いる", "page": 3},
{"word": "eight", "meaning": "8", "page": 3},
{"word": "sometimes", "meaning": "時々", "page": 3},
{"word": "go", "meaning": "行く", "page": 3},
{"word": "visit", "meaning": "訪問する", "page": 3},
{"word": "to", "meaning": "～へ", "page": 3},
{"word": "September", "meaning": "9月", "page": 3},
{"word": "one", "meaning": "1つの", "page": 3},
{"word": "apple", "meaning": "リンゴ", "page": 3},
{"word": "evening", "meaning": "夕方", "page": 3},
{"word": "big", "meaning": "大きい", "page": 3},
{"word": "left", "meaning": "左", "page": 3},
{"word": "strong", "meaning": "強い", "page": 3},
{"word": "kind", "meaning": "種類", "page": 3},
{"word": "cloudy", "meaning": "曇った", "page": 3},
{"word": "rabbit", "meaning": "ウサギ", "page": 3},
{"word": "bicycle", "meaning": "自転車", "page": 3},
{"word": "sport", "meaning": "スポーツ", "page": 3},
{"word": "brown", "meaning": "茶色の", "page": 3},
{"word": "leg", "meaning": "脚", "page": 3},
{"word": "street", "meaning": "通り", "page": 4},
{"word": "dish", "meaning": "皿", "page": 4},
{"word": "teach", "meaning": "教える", "page": 4},
{"word": "heart", "meaning": "心", "page": 4},
{"word": "English", "meaning": "英語", "page": 4},
{"word": "bath", "meaning": "風呂", "page": 4},
{"word": "mouse", "meaning": "ネズミ", "page": 4},
{"word": "math", "meaning": "数学", "page": 4},
{"word": "same", "meaning": "同じ", "page": 4},
{"word": "tooth", "meaning": "歯", "page": 4},
{"word": "newspaper", "meaning": "新聞", "page": 4},
{"word": "dream", "meaning": "夢", "page": 4},
{"word": "draw", "meaning": "描く", "page": 4},
{"word": "body", "meaning": "身体", "page": 4},
{"word": "clothes", "meaning": "服", "page": 4},
{"word": "musician", "meaning": "音楽家", "page": 4},
{"word": "monkey", "meaning": "サル", "page": 4},
{"word": "fall", "meaning": "落ちる，降りる", "page": 4},
{"word": "join", "meaning": "参加する", "page": 4},
{"word": "and", "meaning": "～と", "page": 4},
{"word": "bear", "meaning": "クマ", "page": 4},
{"word": "water", "meaning": "水", "page": 4},
{"word": "nature", "meaning": "自然", "page": 4},
{"word": "tired", "meaning": "疲れて", "page": 4},
{"word": "chicken", "meaning": "鶏肉", "page": 4},
{"word": "mountain", "meaning": "山", "page": 4},
{"word": "rainy", "meaning": "雨降の", "page": 4},
{"word": "bridge", "meaning": "橋", "page": 4},
{"word": "lake", "meaning": "湖", "page": 4},
{"word": "fun", "meaning": "楽しみ", "page": 4},
{"word": "grandmother", "meaning": "祖母", "page": 4},
{"word": "great", "meaning": "素晴らしい、広大な", "page": 4},
{"word": "date", "meaning": "日付", "page": 4},
{"word": "interesting", "meaning": "面白い", "page": 4},
{"word": "job", "meaning": "仕事", "page": 4},
{"word": "sea", "meaning": "海", "page": 4},
{"word": "dictionary", "meaning": "辞書", "page": 4},
{"word": "turn", "meaning": "曲がる、回る、変化する", "page": 4},
{"word": "farmer", "meaning": "農家", "page": 4},
{"word": "well", "meaning": "健康な", "page": 4},
{"word": "shop", "meaning": "店", "page": 4},
{"word": "clock", "meaning": "置き時計", "page": 4},
{"word": "favorite", "meaning": "お気に入りの", "page": 4},
{"word": "hundred", "meaning": "百", "page": 4},
{"word": "mouth", "meaning": "口", "page": 4},
{"word": "sit", "meaning": "着席する", "page": 4},
{"word": "train", "meaning": "列車", "page": 4},
{"word": "face", "meaning": "顔", "page": 4},
{"word": "difficult", "meaning": "難しい", "page": 4},
{"word": "ear", "meaning": "耳", "page": 4},
{"word": "travel", "meaning": "旅行", "page": 4},
{"word": "listen", "meaning": "聴く", "page": 4},
{"word": "museum", "meaning": "博物館", "page": 4},
{"word": "island", "meaning": "島", "page": 4},
{"word": "talk", "meaning": "話す", "page": 4},
{"word": "salad", "meaning": "サラダ", "page": 4},
{"word": "jump", "meaning": "跳ぶ", "page": 4},
{"word": "pig", "meaning": "ブタ", "page": 4},
{"word": "tea", "meaning": "お茶", "page": 4},
{"word": "star", "meaning": "星、スター", "page": 4},
{"word": "beef", "meaning": "牛肉", "page": 4},
{"word": "nose", "meaning": "鼻", "page": 4},
{"word": "horse", "meaning": "馬", "page": 4},
{"word": "hat", "meaning": "帽子", "page": 4},
{"word": "think", "meaning": "考える", "page": 4},
{"word": "excuse", "meaning": "許す", "page": 4},
{"word": "animal", "meaning": "動物", "page": 4},
{"word": "trip", "meaning": "旅行", "page": 4},
{"word": "vacation", "meaning": "休暇", "page": 4},
{"word": "take", "meaning": "取る", "page": 4},
{"word": "textbook", "meaning": "教科書", "page": 4},
{"word": "life", "meaning": "生活", "page": 4},
{"word": "practice", "meaning": "練習する", "page": 4},
{"word": "clean", "meaning": "きれいな", "page": 4},
{"word": "wonderful", "meaning": "すばらしい", "page": 4},
{"word": "head", "meaning": "頭", "page": 4},
{"word": "classroom", "meaning": "教室", "page": 4},
{"word": "shoulder", "meaning": "肩", "page": 4},
{"word": "vegetable", "meaning": "野菜", "page": 4},
{"word": "food", "meaning": "食べ物", "page": 4},
{"word": "future", "meaning": "未来", "page": 4},
{"word": "king", "meaning": "王様", "page": 5},
{"word": "birthday", "meaning": "誕生日", "page": 5},
{"word": "river", "meaning": "川", "page": 5},
{"word": "can", "meaning": "～できる", "page": 5},
{"word": "ship", "meaning": "船", "page": 5},
{"word": "eye", "meaning": "目", "page": 5},
{"word": "grandfather", "meaning": "祖父", "page": 5},
{"word": "different", "meaning": "違った", "page": 5},
{"word": "soup", "meaning": "スープ", "page": 5},
{"word": "second", "meaning": "秒", "page": 5},
{"word": "frog", "meaning": "カエル", "page": 5},
{"word": "first", "meaning": "1番目", "page": 5},
{"word": "festival", "meaning": "祭", "page": 5},
{"word": "knee", "meaning": "ひざ", "page": 5},
{"word": "snowy", "meaning": "雪の降る", "page": 5},
{"word": "weather", "meaning": "天気", "page": 5},
{"word": "queen", "meaning": "女王", "page": 5},
{"word": "event", "meaning": "出来事", "page": 5},
{"word": "exciting", "meaning": "興奮させる", "page": 5},
{"word": "never", "meaning": "1度もない", "page": 5},
{"word": "with", "meaning": "と一緒に", "page": 5},
{"word": "brush", "meaning": "をみがく", "page": 5},
{"word": "really", "meaning": "本当に", "page": 5},
{"word": "luck", "meaning": "運", "page": 5},
{"word": "guess", "meaning": "推測する", "page": 5},
{"word": "umbrella", "meaning": "傘", "page": 5},
{"word": "grape", "meaning": "ブドウ", "page": 5},
{"word": "tower", "meaning": "塔", "page": 5},
{"word": "snake", "meaning": "蛇", "page": 5},
{"word": "hard", "meaning": "一生懸命に", "page": 5},
{"word": "hard", "meaning": "一生懸命に", "page": 5},
{"word": "scientist", "meaning": "科学者", "page": 5},
{"word": "cute", "meaning": "可愛い", "page": 5},
{"word": "straight", "meaning": "まっすぐに", "page": 5},
{"word": "funny", "meaning": "可笑しい", "page": 5},
{"word": "at", "meaning": "～で", "page": 5},
{"word": "third", "meaning": "3番目", "page": 5},
{"word": "zoo", "meaning": "動物園", "page": 5},
{"word": "delicious", "meaning": "おいしい", "page": 5},
{"word": "down", "meaning": "下に", "page": 5},
{"word": "beach", "meaning": "砂浜", "page": 5},
{"word": "be interested in", "meaning": "に興味がある", "page": 5},
{"word": "on", "meaning": "の上に", "page": 5},
{"word": "who", "meaning": "だれ", "page": 5},
{"word": "what", "meaning": "何", "page": 5},
{"word": "am", "meaning": "いる、ある", "page": 5},
{"word": "under", "meaning": "下の", "page": 5},
{"word": "for", "meaning": "のために", "page": 5},
{"word": "from", "meaning": "～から", "page": 5},
{"word": "let's", "meaning": "～しよう", "page": 5},
{"word": "learn about", "meaning": "について学ぶ", "page": 5},
{"word": "purple", "meaning": "紫色", "page": 5},
{"word": "ruler", "meaning": "定規", "page": 5},
{"word": "memory", "meaning": "記憶", "page": 5},
{"word": "take out", "meaning": "持ち帰り", "page": 5},
{"word": "How about", "meaning": "はどうですか？", "page": 5},
{"word": "take a rest", "meaning": "休憩する", "page": 5},
{"word": "sunny", "meaning": "晴れた", "page": 5},
{"word": "subway", "meaning": "地下鉄", "page": 5},
{"word": "to go", "meaning": "持ち帰り", "page": 5},
{"word": "on weekends", "meaning": "週末に", "page": 5},
{"word": "airplane", "meaning": "飛行機", "page": 5},
{"word": "learn a lot from", "meaning": "からたくさん学ぶ", "page": 5},
{"word": "walk to", "meaning": "へ歩いて行く", "page": 5},
{"word": "world", "meaning": "世界、地球", "page": 5},
{"word": "on your left", "meaning": "左側に", "page": 5},
{"word": "for here", "meaning": "ここで食べる", "page": 5},
{"word": "drum", "meaning": "太鼓", "page": 5},
{"word": "on the way", "meaning": "道の途中で", "page": 5},
{"word": "stand up", "meaning": "立つ", "page": 5},
{"word": "at noon", "meaning": "正午に", "page": 5},
{"word": "farewell party", "meaning": "送別会", "page": 5},
{"word": "temple", "meaning": "お寺", "page": 5},
{"word": "by", "meaning": "のそばに、によって", "page": 5},
{"word": "field trip", "meaning": "遠足", "page": 5},
{"word": "elementary school", "meaning": "小学校", "page": 5},
{"word": "high school", "meaning": "高校", "page": 5},
{"word": "wait for", "meaning": "を待つ", "page": 5},
{"word": "high school", "meaning": "高校", "page": 5},
{"word": "bookstore", "meaning": "本屋", "page": 5},
{"word": "school festival", "meaning": "文化祭", "page": 5},
{"word": "soft", "meaning": "柔らかい", "page": 6},
{"word": "and so on", "meaning": "などなど", "page": 6},
{"word": "be", "meaning": "である", "page": 6},
{"word": "say again", "meaning": "もう一度言う", "page": 6},
{"word": "get up", "meaning": "起きる", "page": 6},
{"word": "worry about", "meaning": "について心配する", "page": 6},
{"word": "spell", "meaning": "を綴る", "page": 6},
{"word": "check ～ out", "meaning": "を確認する", "page": 6},
{"word": "with a smile", "meaning": "笑顔で", "page": 6},
{"word": "reading", "meaning": "読書", "page": 6},
{"word": "entrance ceremony", "meaning": "入学式", "page": 6},
{"word": "sweet", "meaning": "甘い", "page": 6},
{"word": "go straight", "meaning": "まっすぐ行く", "page": 6},
{"word": "junior high school", "meaning": "中学校", "page": 6},
{"word": "by bus", "meaning": "バスで", "page": 6},
{"word": "write down", "meaning": "書く", "page": 6},
{"word": "go back to", "meaning": "に戻る", "page": 6},
{"word": "by car", "meaning": "車まで", "page": 6},
{"word": "tiger", "meaning": "トラ", "page": 6},
{"word": "was", "meaning": "でした", "page": 6},
{"word": "look at", "meaning": "を見る", "page": 6},
{"word": "sit down", "meaning": "座る", "page": 6},
{"word": "stay up", "meaning": "起きている", "page": 6},
{"word": "shopping", "meaning": "買い物", "page": 6},
{"word": "classmate", "meaning": "同級生", "page": 6},
{"word": "out", "meaning": "外に", "page": 6},
{"word": "drama", "meaning": "劇", "page": 6},
{"word": "bean", "meaning": "豆", "page": 6},
{"word": "Japanese", "meaning": "日本人", "page": 6},
{"word": "be(get) excited", "meaning": "興奮をする", "page": 6},
{"word": "listen to", "meaning": "聴く", "page": 6},
{"word": "have a headache", "meaning": "頭痛がする", "page": 6},
{"word": "telephone", "meaning": "電話", "page": 6},
{"word": "on your right", "meaning": "右側に", "page": 6},
{"word": "about", "meaning": "について、に関する", "page": 6},
{"word": "between A and B", "meaning": "AとBの間", "page": 6},
{"word": "supermarket", "meaning": "スーパー", "page": 6},
{"word": "help with", "meaning": "を助ける", "page": 6},
{"word": "bike", "meaning": "自転車", "page": 6}
];
const intermediateWords = [
];
const advancedWords = [
];
const Level4ofkoreanschool = [
];
const Level5ofkoreanschool = [
];
const expressionUpWords = [
];