const level5Words = [
{"word": "one", "meaning": "一つの", "page": 1},
{"word": "the", "meaning": "その", "page": 1},
{"word": "you", "meaning": "あなたは", "page": 1},
{"word": "my", "meaning": "私の", "page": 1},
{"word": "father", "meaning": "父親", "page": 1},
{"word": "do", "meaning": "する", "page": 1},
{"word": "your", "meaning": "あなたの", "page": 1},
{"word": "in", "meaning": "の中に", "page": 1},
{"word": "read", "meaning": "読む", "page": 1},
{"word": "he", "meaning": "彼は", "page": 1},
{"word": "see", "meaning": "見る", "page": 1},
{"word": "it", "meaning": "それは", "page": 1},
{"word": "mother", "meaning": "母", "page": 1},
{"word": "name", "meaning": "名前", "page": 1},
{"word": "like", "meaning": "好む", "page": 1},
{"word": "how", "meaning": "どのぐらい", "page": 1},
{"word": "school", "meaning": "学校", "page": 1},
{"word": "January", "meaning": "1月", "page": 1},
{"word": "all", "meaning": "全部、全員、全て、みな", "page": 1},
{"word": "old", "meaning": "古い", "page": 1},
{"word": "fruit", "meaning": "果物", "page": 1},
{"word": "speak", "meaning": "話す", "page": 1},
{"word": "where", "meaning": "どこに", "page": 1},
{"word": "long", "meaning": "長い", "page": 1},
{"word": "study", "meaning": "勉強する", "page": 1},
{"word": "chair", "meaning": "椅子", "page": 1},
{"word": "very", "meaning": "非常に", "page": 1},
{"word": "I", "meaning": "私は", "page": 1},
{"word": "our", "meaning": "私たちの", "page": 1},
{"word": "year", "meaning": "年", "page": 1},
{"word": "when", "meaning": "～するとき", "page": 1},
{"word": "a lot of", "meaning": "たくさんの", "page": 1},
{"word": "nice", "meaning": "良い", "page": 1},
{"word": "sing", "meaning": "歌う", "page": 1},
{"word": "fine", "meaning": "元気な、晴れた", "page": 1},
{"word": "right", "meaning": "右に", "page": 1},
{"word": "want", "meaning": "欲しい", "page": 1},
{"word": "red", "meaning": "赤い", "page": 1},
{"word": "much", "meaning": "たくさん", "page": 1},
{"word": "here", "meaning": "ここに", "page": 1},
{"word": "July", "meaning": "7月", "page": 1},
{"word": "cold", "meaning": "冷たい", "page": 1},
{"word": "write", "meaning": "書く、手紙を書く", "page": 1},
{"word": "station", "meaning": "駅", "page": 1},
{"word": "color", "meaning": "色", "page": 1},
{"word": "this", "meaning": "この", "page": 1},
{"word": "she", "meaning": "彼女は", "page": 1},
{"word": "look", "meaning": "見る", "page": 1},
{"word": "many", "meaning": "多くの", "page": 1},
{"word": "two", "meaning": "2", "page": 1},
{"word": "teacher", "meaning": "先生", "page": 1},
{"word": "morning", "meaning": "朝", "page": 1},
{"word": "use", "meaning": "使う", "page": 1},
{"word": "run", "meaning": "を主催する", "page": 1},
{"word": "hungry", "meaning": "空腹の", "page": 1},
{"word": "fish", "meaning": "魚", "page": 1},
{"word": "lunch", "meaning": "昼食", "page": 1},
{"word": "have", "meaning": "持っている", "page": 1},
{"word": "eat", "meaning": "食べる", "page": 1},
{"word": "know", "meaning": "知っている", "page": 1},
{"word": "usually", "meaning": "普通は", "page": 1},
{"word": "season", "meaning": "季節", "page": 1},
{"word": "book", "meaning": "本", "page": 1},
{"word": "winter", "meaning": "冬", "page": 1},
{"word": "stop", "meaning": "止める", "page": 1},
{"word": "three", "meaning": "3", "page": 1},
{"word": "pencil", "meaning": "鉛筆", "page": 1},
{"word": "please", "meaning": "喜ばせる", "page": 1},
{"word": "wall", "meaning": "壁", "page": 1},
{"word": "meet", "meaning": "会う", "page": 1},
{"word": "May", "meaning": "5月", "page": 1},
{"word": "ride", "meaning": "乗る", "page": 1},
{"word": "six", "meaning": "6", "page": 1},
{"word": "always", "meaning": "いつも", "page": 1},
{"word": "drink", "meaning": "飲む", "page": 1},
{"word": "four", "meaning": "4", "page": 1},
{"word": "sister", "meaning": "姉妹", "page": 1},
{"word": "hospital", "meaning": "病院", "page": 1},
{"word": "park", "meaning": "公園", "page": 1},
{"word": "baseball", "meaning": "野球", "page": 1},
{"word": "wash", "meaning": "洗う", "page": 2},
{"word": "cake", "meaning": "ケーキ", "page": 2},
{"word": "bag", "meaning": "カバン", "page": 2},
{"word": "Tuesday", "meaning": "火曜日", "page": 2},
{"word": "try", "meaning": "試す", "page": 2},
{"word": "cook", "meaning": "料理する", "page": 2},
{"word": "watch", "meaning": "見る", "page": 2},
{"word": "nurse", "meaning": "看護師", "page": 2},
{"word": "five", "meaning": "5", "page": 2},
{"word": "seventeen", "meaning": "17", "page": 2},
{"word": "table", "meaning": "机", "page": 2},
{"word": "place", "meaning": "場所", "page": 2},
{"word": "cup", "meaning": "カップ", "page": 2},
{"word": "green", "meaning": "緑", "page": 2},
{"word": "we", "meaning": "私たちは", "page": 2},
{"word": "fifty", "meaning": "50", "page": 2},
{"word": "eleven", "meaning": "11", "page": 2},
{"word": "picture", "meaning": "絵、写真", "page": 2},
{"word": "happy", "meaning": "幸福な", "page": 2},
{"word": "Thursday", "meaning": "木曜日", "page": 2},
{"word": "Japan", "meaning": "日本", "page": 2},
{"word": "hot", "meaning": "暑い", "page": 2},
{"word": "leave", "meaning": "去る，残す，置いて行く", "page": 2},
{"word": "garbage", "meaning": "ゴミ", "page": 2},
{"word": "hand", "meaning": "手", "page": 2},
{"word": "thirty", "meaning": "30", "page": 2},
{"word": "dinner", "meaning": "夕食", "page": 2},
{"word": "Saturday", "meaning": "土曜日", "page": 2},
{"word": "thirteen", "meaning": "13", "page": 2},
{"word": "fourteen", "meaning": "14", "page": 2},
{"word": "sorry", "meaning": "ごめんなさい", "page": 2},
{"word": "large", "meaning": "大きい、広い", "page": 2},
{"word": "enjoy", "meaning": "楽しむ", "page": 2},
{"word": "flower", "meaning": "花", "page": 2},
{"word": "nineteen", "meaning": "19", "page": 2},
{"word": "night", "meaning": "夜", "page": 2},
{"word": "sheep", "meaning": "ヒツジ", "page": 2},
{"word": "car", "meaning": "自動車", "page": 2},
{"word": "library", "meaning": "図書館", "page": 2},
{"word": "March", "meaning": "3月", "page": 2},
{"word": "again", "meaning": "もう一度、再び、また", "page": 2},
{"word": "beautiful", "meaning": "美しい", "page": 2},
{"word": "Friday", "meaning": "金曜日", "page": 2},
{"word": "cool", "meaning": "かっこいい", "page": 2},
{"word": "day", "meaning": "日", "page": 2},
{"word": "October", "meaning": "10月", "page": 2},
{"word": "get", "meaning": "得る", "page": 2},
{"word": "map", "meaning": "地図", "page": 2},
{"word": "family", "meaning": "家族", "page": 2},
{"word": "boy", "meaning": "少年", "page": 2},
{"word": "white", "meaning": "白", "page": 2},
{"word": "house", "meaning": "家", "page": 2},
{"word": "Monday", "meaning": "月曜日", "page": 2},
{"word": "country", "meaning": "国", "page": 2},
{"word": "box", "meaning": "箱", "page": 2},
{"word": "bread", "meaning": "パン", "page": 2},
{"word": "sixteen", "meaning": "16", "page": 2},
{"word": "eighteen", "meaning": "18", "page": 2},
{"word": "put", "meaning": "置く", "page": 2},
{"word": "month", "meaning": "月", "page": 2},
{"word": "cap", "meaning": "帽子", "page": 2},
{"word": "fast", "meaning": "速い", "page": 2},
{"word": "April", "meaning": "4月", "page": 2},
{"word": "autumn", "meaning": "秋", "page": 2},
{"word": "buy", "meaning": "買う", "page": 2},
{"word": "swim", "meaning": "泳ぐ", "page": 2},
{"word": "city", "meaning": "市", "page": 2},
{"word": "room", "meaning": "部屋", "page": 2},
{"word": "brother", "meaning": "兄弟", "page": 2},
{"word": "walk", "meaning": "散歩", "page": 2},
{"word": "August", "meaning": "8月", "page": 2},
{"word": "summer", "meaning": "夏", "page": 2},
{"word": "blue", "meaning": "青い", "page": 2},
{"word": "dog", "meaning": "イヌ", "page": 2},
{"word": "ten", "meaning": "10", "page": 2},
{"word": "eighty", "meaning": "80", "page": 2},
{"word": "doctor", "meaning": "医者", "page": 2},
{"word": "friend", "meaning": "友達", "page": 2},
{"word": "sleep", "meaning": "眠る", "page": 2},
{"word": "busy", "meaning": "忙しい", "page": 2},
{"word": "play", "meaning": "劇", "page": 3},
{"word": "help", "meaning": "助ける", "page": 3},
{"word": "live", "meaning": "住む", "page": 3},
{"word": "February", "meaning": "2月", "page": 3},
{"word": "not", "meaning": "～でない", "page": 3},
{"word": "way", "meaning": "道、方法", "page": 3},
{"word": "fifteen", "meaning": "15", "page": 3},
{"word": "stand", "meaning": "を我慢する", "page": 3},
{"word": "small", "meaning": "小さい", "page": 3},
{"word": "easy", "meaning": "簡単な", "page": 3},
{"word": "bird", "meaning": "鳥", "page": 3},
{"word": "time", "meaning": "時、～回", "page": 3},
{"word": "welcome", "meaning": "歓迎する", "page": 3},
{"word": "best", "meaning": "一番良い", "page": 3},
{"word": "homework", "meaning": "宿題", "page": 3},
{"word": "November", "meaning": "11月", "page": 3},
{"word": "December", "meaning": "12月", "page": 3},
{"word": "Wednesday", "meaning": "水曜日", "page": 3},
{"word": "June", "meaning": "6月", "page": 3},
{"word": "together", "meaning": "一緒に", "page": 3},
{"word": "tree", "meaning": "木", "page": 3},
{"word": "black", "meaning": "黒い", "page": 3},
{"word": "cow", "meaning": "ウシ", "page": 3},
{"word": "Sunday", "meaning": "日曜日", "page": 3},
{"word": "yellow", "meaning": "黄色", "page": 3},
{"word": "spring", "meaning": "春", "page": 3},
{"word": "make", "meaning": "作る、～を～にするする", "page": 3},
{"word": "desk", "meaning": "机", "page": 3},
{"word": "science", "meaning": "科学", "page": 3},
{"word": "sixty", "meaning": "60", "page": 3},
{"word": "twelve", "meaning": "12", "page": 3},
{"word": "cat", "meaning": "猫", "page": 3},
{"word": "window", "meaning": "窓", "page": 3},
{"word": "subject", "meaning": "科目、題目", "page": 3},
{"word": "me", "meaning": "私を(に)", "page": 3},
{"word": "town", "meaning": "街", "page": 3},
{"word": "that", "meaning": "あれ", "page": 3},
{"word": "seven", "meaning": "7", "page": 3},
{"word": "afternoon", "meaning": "午後", "page": 3},
{"word": "why", "meaning": "なぜ", "page": 3},
{"word": "nine", "meaning": "9", "page": 3},
{"word": "girl", "meaning": "少女", "page": 3},
{"word": "up", "meaning": "上へ", "page": 3},
{"word": "too", "meaning": "～もまた", "page": 3},
{"word": "new", "meaning": "新しい", "page": 3},
{"word": "player", "meaning": "選手", "page": 3},
{"word": "seventy", "meaning": "70", "page": 3},
{"word": "egg", "meaning": "卵", "page": 3},
{"word": "ninety", "meaning": "90", "page": 3},
{"word": "forty", "meaning": "40", "page": 3},
{"word": "good", "meaning": "良い", "page": 3},
{"word": "twenty", "meaning": "20", "page": 3},
{"word": "breakfast", "meaning": "朝食", "page": 3},
{"word": "everyone", "meaning": "みんな", "page": 3},
{"word": "number", "meaning": "数", "page": 3},
{"word": "famous", "meaning": "有名な", "page": 3},
{"word": "short", "meaning": "短い", "page": 3},
{"word": "sad", "meaning": "悲しい", "page": 3},
{"word": "is", "meaning": "ある、いる", "page": 3},
{"word": "eight", "meaning": "8", "page": 3},
{"word": "sometimes", "meaning": "時々", "page": 3},
{"word": "go", "meaning": "行く", "page": 3},
{"word": "visit", "meaning": "訪問する", "page": 3},
{"word": "to", "meaning": "～へ", "page": 3},
{"word": "September", "meaning": "9月", "page": 3},
{"word": "one", "meaning": "1つの", "page": 3},
{"word": "apple", "meaning": "リンゴ", "page": 3},
{"word": "evening", "meaning": "夕方", "page": 3},
{"word": "big", "meaning": "大きい", "page": 3},
{"word": "left", "meaning": "左", "page": 3},
{"word": "strong", "meaning": "強い", "page": 3},
{"word": "kind", "meaning": "種類", "page": 3},
{"word": "cloudy", "meaning": "曇った", "page": 3},
{"word": "rabbit", "meaning": "ウサギ", "page": 3},
{"word": "bicycle", "meaning": "自転車", "page": 3},
{"word": "sport", "meaning": "スポーツ", "page": 3},
{"word": "brown", "meaning": "茶色の", "page": 3},
{"word": "leg", "meaning": "脚", "page": 3},
{"word": "street", "meaning": "通り", "page": 4},
{"word": "dish", "meaning": "皿", "page": 4},
{"word": "teach", "meaning": "教える", "page": 4},
{"word": "heart", "meaning": "心", "page": 4},
{"word": "English", "meaning": "英語", "page": 4},
{"word": "bath", "meaning": "風呂", "page": 4},
{"word": "mouse", "meaning": "ネズミ", "page": 4},
{"word": "math", "meaning": "数学", "page": 4},
{"word": "same", "meaning": "同じ", "page": 4},
{"word": "tooth", "meaning": "歯", "page": 4},
{"word": "newspaper", "meaning": "新聞", "page": 4},
{"word": "dream", "meaning": "夢", "page": 4},
{"word": "draw", "meaning": "描く", "page": 4},
{"word": "body", "meaning": "身体", "page": 4},
{"word": "clothes", "meaning": "服", "page": 4},
{"word": "musician", "meaning": "音楽家", "page": 4},
{"word": "monkey", "meaning": "サル", "page": 4},
{"word": "fall", "meaning": "落ちる，降りる", "page": 4},
{"word": "join", "meaning": "参加する", "page": 4},
{"word": "and", "meaning": "～と", "page": 4},
{"word": "bear", "meaning": "クマ", "page": 4},
{"word": "water", "meaning": "水", "page": 4},
{"word": "nature", "meaning": "自然", "page": 4},
{"word": "tired", "meaning": "疲れて", "page": 4},
{"word": "chicken", "meaning": "鶏肉", "page": 4},
{"word": "mountain", "meaning": "山", "page": 4},
{"word": "rainy", "meaning": "雨降の", "page": 4},
{"word": "bridge", "meaning": "橋", "page": 4},
{"word": "lake", "meaning": "湖", "page": 4},
{"word": "fun", "meaning": "楽しみ", "page": 4},
{"word": "grandmother", "meaning": "祖母", "page": 4},
{"word": "great", "meaning": "素晴らしい、広大な", "page": 4},
{"word": "date", "meaning": "日付", "page": 4},
{"word": "interesting", "meaning": "面白い", "page": 4},
{"word": "job", "meaning": "仕事", "page": 4},
{"word": "sea", "meaning": "海", "page": 4},
{"word": "dictionary", "meaning": "辞書", "page": 4},
{"word": "turn", "meaning": "曲がる、回る、変化する", "page": 4},
{"word": "farmer", "meaning": "農家", "page": 4},
{"word": "well", "meaning": "健康な", "page": 4},
{"word": "shop", "meaning": "店", "page": 4},
{"word": "clock", "meaning": "置き時計", "page": 4},
{"word": "favorite", "meaning": "お気に入りの", "page": 4},
{"word": "hundred", "meaning": "百", "page": 4},
{"word": "mouth", "meaning": "口", "page": 4},
{"word": "sit", "meaning": "着席する", "page": 4},
{"word": "train", "meaning": "列車", "page": 4},
{"word": "face", "meaning": "顔", "page": 4},
{"word": "difficult", "meaning": "難しい", "page": 4},
{"word": "ear", "meaning": "耳", "page": 4},
{"word": "travel", "meaning": "旅行", "page": 4},
{"word": "listen", "meaning": "聴く", "page": 4},
{"word": "museum", "meaning": "博物館", "page": 4},
{"word": "island", "meaning": "島", "page": 4},
{"word": "talk", "meaning": "話す", "page": 4},
{"word": "salad", "meaning": "サラダ", "page": 4},
{"word": "jump", "meaning": "跳ぶ", "page": 4},
{"word": "pig", "meaning": "ブタ", "page": 4},
{"word": "tea", "meaning": "お茶", "page": 4},
{"word": "star", "meaning": "星、スター", "page": 4},
{"word": "beef", "meaning": "牛肉", "page": 4},
{"word": "nose", "meaning": "鼻", "page": 4},
{"word": "horse", "meaning": "馬", "page": 4},
{"word": "hat", "meaning": "帽子", "page": 4},
{"word": "think", "meaning": "考える", "page": 4},
{"word": "excuse", "meaning": "許す", "page": 4},
{"word": "animal", "meaning": "動物", "page": 4},
{"word": "trip", "meaning": "旅行", "page": 4},
{"word": "vacation", "meaning": "休暇", "page": 4},
{"word": "take", "meaning": "取る", "page": 4},
{"word": "textbook", "meaning": "教科書", "page": 4},
{"word": "life", "meaning": "生活", "page": 4},
{"word": "practice", "meaning": "練習する", "page": 4},
{"word": "clean", "meaning": "きれいな", "page": 4},
{"word": "wonderful", "meaning": "すばらしい", "page": 4},
{"word": "head", "meaning": "頭", "page": 4},
{"word": "classroom", "meaning": "教室", "page": 4},
{"word": "shoulder", "meaning": "肩", "page": 4},
{"word": "vegetable", "meaning": "野菜", "page": 4},
{"word": "food", "meaning": "食べ物", "page": 4},
{"word": "future", "meaning": "未来", "page": 4},
{"word": "king", "meaning": "王様", "page": 5},
{"word": "birthday", "meaning": "誕生日", "page": 5},
{"word": "river", "meaning": "川", "page": 5},
{"word": "can", "meaning": "～できる", "page": 5},
{"word": "ship", "meaning": "船", "page": 5},
{"word": "eye", "meaning": "目", "page": 5},
{"word": "grandfather", "meaning": "祖父", "page": 5},
{"word": "different", "meaning": "違った", "page": 5},
{"word": "soup", "meaning": "スープ", "page": 5},
{"word": "second", "meaning": "秒", "page": 5},
{"word": "frog", "meaning": "カエル", "page": 5},
{"word": "first", "meaning": "1番目", "page": 5},
{"word": "festival", "meaning": "祭", "page": 5},
{"word": "knee", "meaning": "ひざ", "page": 5},
{"word": "snowy", "meaning": "雪の降る", "page": 5},
{"word": "weather", "meaning": "天気", "page": 5},
{"word": "queen", "meaning": "女王", "page": 5},
{"word": "event", "meaning": "出来事", "page": 5},
{"word": "exciting", "meaning": "興奮させる", "page": 5},
{"word": "never", "meaning": "1度もない", "page": 5},
{"word": "with", "meaning": "と一緒に", "page": 5},
{"word": "brush", "meaning": "をみがく", "page": 5},
{"word": "really", "meaning": "本当に", "page": 5},
{"word": "luck", "meaning": "運", "page": 5},
{"word": "guess", "meaning": "推測する", "page": 5},
{"word": "umbrella", "meaning": "傘", "page": 5},
{"word": "grape", "meaning": "ブドウ", "page": 5},
{"word": "tower", "meaning": "塔", "page": 5},
{"word": "snake", "meaning": "蛇", "page": 5},
{"word": "hard", "meaning": "一生懸命に", "page": 5},
{"word": "hard", "meaning": "一生懸命に", "page": 5},
{"word": "scientist", "meaning": "科学者", "page": 5},
{"word": "cute", "meaning": "可愛い", "page": 5},
{"word": "straight", "meaning": "まっすぐに", "page": 5},
{"word": "funny", "meaning": "可笑しい", "page": 5},
{"word": "at", "meaning": "～で", "page": 5},
{"word": "third", "meaning": "3番目", "page": 5},
{"word": "zoo", "meaning": "動物園", "page": 5},
{"word": "delicious", "meaning": "おいしい", "page": 5},
{"word": "down", "meaning": "下に", "page": 5},
{"word": "beach", "meaning": "砂浜", "page": 5},
{"word": "be interested in", "meaning": "に興味がある", "page": 5},
{"word": "on", "meaning": "の上に", "page": 5},
{"word": "who", "meaning": "だれ", "page": 5},
{"word": "what", "meaning": "何", "page": 5},
{"word": "am", "meaning": "いる、ある", "page": 5},
{"word": "under", "meaning": "下の", "page": 5},
{"word": "for", "meaning": "のために", "page": 5},
{"word": "from", "meaning": "～から", "page": 5},
{"word": "let's", "meaning": "～しよう", "page": 5},
{"word": "learn about", "meaning": "について学ぶ", "page": 5},
{"word": "purple", "meaning": "紫色", "page": 5},
{"word": "ruler", "meaning": "定規", "page": 5},
{"word": "memory", "meaning": "記憶", "page": 5},
{"word": "take out", "meaning": "持ち帰り", "page": 5},
{"word": "How about", "meaning": "はどうですか？", "page": 5},
{"word": "take a rest", "meaning": "休憩する", "page": 5},
{"word": "sunny", "meaning": "晴れた", "page": 5},
{"word": "subway", "meaning": "地下鉄", "page": 5},
{"word": "to go", "meaning": "持ち帰り", "page": 5},
{"word": "on weekends", "meaning": "週末に", "page": 5},
{"word": "airplane", "meaning": "飛行機", "page": 5},
{"word": "learn a lot from", "meaning": "からたくさん学ぶ", "page": 5},
{"word": "walk to", "meaning": "へ歩いて行く", "page": 5},
{"word": "world", "meaning": "世界、地球", "page": 5},
{"word": "on your left", "meaning": "左側に", "page": 5},
{"word": "for here", "meaning": "ここで食べる", "page": 5},
{"word": "drum", "meaning": "太鼓", "page": 5},
{"word": "on the way", "meaning": "道の途中で", "page": 5},
{"word": "stand up", "meaning": "立つ", "page": 5},
{"word": "at noon", "meaning": "正午に", "page": 5},
{"word": "farewell party", "meaning": "送別会", "page": 5},
{"word": "temple", "meaning": "お寺", "page": 5},
{"word": "by", "meaning": "のそばに、によって", "page": 5},
{"word": "field trip", "meaning": "遠足", "page": 5},
{"word": "elementary school", "meaning": "小学校", "page": 5},
{"word": "high school", "meaning": "高校", "page": 5},
{"word": "wait for", "meaning": "を待つ", "page": 5},
{"word": "high school", "meaning": "高校", "page": 5},
{"word": "bookstore", "meaning": "本屋", "page": 5},
{"word": "school festival", "meaning": "文化祭", "page": 5},
{"word": "soft", "meaning": "柔らかい", "page": 6},
{"word": "and so on", "meaning": "などなど", "page": 6},
{"word": "be", "meaning": "である", "page": 6},
{"word": "say again", "meaning": "もう一度言う", "page": 6},
{"word": "get up", "meaning": "起きる", "page": 6},
{"word": "worry about", "meaning": "について心配する", "page": 6},
{"word": "spell", "meaning": "を綴る", "page": 6},
{"word": "check ～ out", "meaning": "を確認する", "page": 6},
{"word": "with a smile", "meaning": "笑顔で", "page": 6},
{"word": "reading", "meaning": "読書", "page": 6},
{"word": "entrance ceremony", "meaning": "入学式", "page": 6},
{"word": "sweet", "meaning": "甘い", "page": 6},
{"word": "go straight", "meaning": "まっすぐ行く", "page": 6},
{"word": "junior high school", "meaning": "中学校", "page": 6},
{"word": "by bus", "meaning": "バスで", "page": 6},
{"word": "write down", "meaning": "書く", "page": 6},
{"word": "go back to", "meaning": "に戻る", "page": 6},
{"word": "by car", "meaning": "車まで", "page": 6},
{"word": "tiger", "meaning": "トラ", "page": 6},
{"word": "was", "meaning": "でした", "page": 6},
{"word": "look at", "meaning": "を見る", "page": 6},
{"word": "sit down", "meaning": "座る", "page": 6},
{"word": "stay up", "meaning": "起きている", "page": 6},
{"word": "shopping", "meaning": "買い物", "page": 6},
{"word": "classmate", "meaning": "同級生", "page": 6},
{"word": "out", "meaning": "外に", "page": 6},
{"word": "drama", "meaning": "劇", "page": 6},
{"word": "bean", "meaning": "豆", "page": 6},
{"word": "Japanese", "meaning": "日本人", "page": 6},
{"word": "be(get) excited", "meaning": "興奮をする", "page": 6},
{"word": "listen to", "meaning": "聴く", "page": 6},
{"word": "have a headache", "meaning": "頭痛がする", "page": 6},
{"word": "telephone", "meaning": "電話", "page": 6},
{"word": "on your right", "meaning": "右側に", "page": 6},
{"word": "about", "meaning": "について、に関する", "page": 6},
{"word": "between A and B", "meaning": "AとBの間", "page": 6},
{"word": "supermarket", "meaning": "スーパー", "page": 6},
{"word": "help with", "meaning": "を助ける", "page": 6},
{"word": "bike", "meaning": "自転車", "page": 6}
];
const level4Words = [
{"word": "other", "meaning": "ほかの", "page": 1},
{"word": "people", "meaning": "人々", "page": 1},
{"word": "end", "meaning": "終わる", "page": 1},
{"word": "last", "meaning": "この前の，最後の", "page": 1},
{"word": "one", "meaning": "1つの", "page": 1},
{"word": "each", "meaning": "各々の", "page": 1},
{"word": "say", "meaning": "言う", "page": 1},
{"word": "talk", "meaning": "話す", "page": 1},
{"word": "question", "meaning": "質問", "page": 1},
{"word": "own", "meaning": "自分の", "page": 1},
{"word": "think", "meaning": "考える", "page": 1},
{"word": "last", "meaning": "最後", "page": 1},
{"word": "rest", "meaning": "休息する", "page": 1},
{"word": "tea", "meaning": "お茶", "page": 1},
{"word": "see", "meaning": "見る", "page": 1},
{"word": "sit", "meaning": "着席する", "page": 1},
{"word": "art", "meaning": "美術，芸術", "page": 1},
{"word": "take", "meaning": "取る", "page": 1},
{"word": "take", "meaning": "連れて行く", "page": 1},
{"word": "rain", "meaning": "雨", "page": 1},
{"word": "foot", "meaning": "足", "page": 1},
{"word": "I", "meaning": "私は", "page": 1},
{"word": "enough", "meaning": "十分な", "page": 1},
{"word": "tell", "meaning": "伝える", "page": 1},
{"word": "shout", "meaning": "叫ぶ", "page": 1},
{"word": "think", "meaning": "思う", "page": 1},
{"word": "five", "meaning": "5", "page": 1},
{"word": "father", "meaning": "父親", "page": 1},
{"word": "fish", "meaning": "魚", "page": 1},
{"word": "animal", "meaning": "動物", "page": 1},
{"word": "such", "meaning": "そのような", "page": 1},
{"word": "answer", "meaning": "答える", "page": 1},
{"word": "right", "meaning": "右に", "page": 1},
{"word": "teach", "meaning": "教える", "page": 1},
{"word": "future", "meaning": "未来", "page": 1},
{"word": "show", "meaning": "見せる", "page": 1},
{"word": "rise", "meaning": "昇る", "page": 1},
{"word": "sea", "meaning": "海", "page": 1},
{"word": "decide", "meaning": "決心する", "page": 1},
{"word": "you", "meaning": "あなたは", "page": 1},
{"word": "right", "meaning": "正しい", "page": 1},
{"word": "exciting", "meaning": "興奮させる", "page": 1},
{"word": "sun", "meaning": "太陽", "page": 1},
{"word": "word", "meaning": "言葉", "page": 1},
{"word": "see", "meaning": "分かる", "page": 1},
{"word": "interesting", "meaning": "面白い", "page": 1},
{"word": "port", "meaning": "港", "page": 1},
{"word": "front", "meaning": "前", "page": 1},
{"word": "hold", "meaning": "握る", "page": 1},
{"word": "remember", "meaning": "思い出す", "page": 1},
{"word": "mountain", "meaning": "山", "page": 1},
{"word": "understand", "meaning": "理解する", "page": 1},
{"word": "river", "meaning": "川", "page": 1},
{"word": "popular", "meaning": "人気の", "page": 1},
{"word": "face", "meaning": "顔", "page": 1},
{"word": "usual", "meaning": "通常の", "page": 1},
{"word": "set", "meaning": "置く", "page": 1},
{"word": "market", "meaning": "市場", "page": 1},
{"word": "what", "meaning": "なに", "page": 1},
{"word": "remember", "meaning": "覚えている", "page": 1},
{"word": "different", "meaning": "違った", "page": 1},
{"word": "watch", "meaning": "見る、視聴する", "page": 1},
{"word": "sure", "meaning": "確信して", "page": 1},
{"word": "same", "meaning": "同じ", "page": 1},
{"word": "mean", "meaning": "意味する", "page": 1},
{"word": "lake", "meaning": "湖", "page": 1},
{"word": "lie", "meaning": "嘘", "page": 1},
{"word": "spend", "meaning": "費やす", "page": 1},
{"word": "war", "meaning": "戦争", "page": 1},
{"word": "wear", "meaning": "着る", "page": 1},
{"word": "kind", "meaning": "種類", "page": 1},
{"word": "tired", "meaning": "疲れて", "page": 1},
{"word": "useful", "meaning": "役に立つ", "page": 1},
{"word": "cloth", "meaning": "服", "page": 1},
{"word": "take", "meaning": "撮影する", "page": 1},
{"word": "ice", "meaning": "氷", "page": 1},
{"word": "leg", "meaning": "脚", "page": 1},
{"word": "enter", "meaning": "入る", "page": 1},
{"word": "health", "meaning": "健康", "page": 1},
{"word": "invite", "meaning": "招待する", "page": 1},
{"word": "loud", "meaning": "騒がしい", "page": 2},
{"word": "hold", "meaning": "握る", "page": 2},
{"word": "fall", "meaning": "落ちる", "page": 2},
{"word": "throw", "meaning": "投げる", "page": 2},
{"word": "tell", "meaning": "伝える", "page": 2},
{"word": "finish", "meaning": "終える", "page": 2},
{"word": "forget", "meaning": "忘れる", "page": 2},
{"word": "snow", "meaning": "雪", "page": 2},
{"word": "water", "meaning": "水", "page": 2},
{"word": "person", "meaning": "人", "page": 2},
{"word": "heart", "meaning": "心", "page": 2},
{"word": "worry", "meaning": "心配させる", "page": 2},
{"word": "wife", "meaning": "妻", "page": 2},
{"word": "meat", "meaning": "肉", "page": 2},
{"word": "well", "meaning": "健康な", "page": 2},
{"word": "a lot of", "meaning": "たくさんの", "page": 2},
{"word": "hundred", "meaning": "百", "page": 2},
{"word": "vacation", "meaning": "休暇", "page": 2},
{"word": "leaf", "meaning": "葉", "page": 2},
{"word": "wish", "meaning": "望む", "page": 2},
{"word": "vegetable", "meaning": "野菜", "page": 2},
{"word": "grandmother", "meaning": "祖母", "page": 2},
{"word": "island", "meaning": "島", "page": 2},
{"word": "hill", "meaning": "丘", "page": 2},
{"word": "tooth", "meaning": "歯", "page": 2},
{"word": "draw", "meaning": "描く", "page": 2},
{"word": "success", "meaning": "成功", "page": 2},
{"word": "wind", "meaning": "風", "page": 2},
{"word": "stone", "meaning": "石", "page": 2},
{"word": "pork", "meaning": "豚肉", "page": 2},
{"word": "build", "meaning": "建てる", "page": 2},
{"word": "pick", "meaning": "選ぶ", "page": 2},
{"word": "inside", "meaning": "内側", "page": 2},
{"word": "factory", "meaning": "工場", "page": 2},
{"word": "roof", "meaning": "屋根", "page": 2},
{"word": "past", "meaning": "過去の", "page": 2},
{"word": "sailor", "meaning": "船員", "page": 2},
{"word": "sugar", "meaning": "砂糖", "page": 2},
{"word": "shoulder", "meaning": "肩", "page": 2},
{"word": "wood", "meaning": "木材", "page": 2},
{"word": "seem", "meaning": "～の様に見える", "page": 2},
{"word": "textbook", "meaning": "教科書", "page": 2},
{"word": "wake", "meaning": "目が覚める", "page": 2},
{"word": "pay", "meaning": "支払う", "page": 2},
{"word": "salt", "meaning": "塩", "page": 2},
{"word": "farmer", "meaning": "農家", "page": 2},
{"word": "cloud", "meaning": "雲", "page": 2},
{"word": "thousand", "meaning": "千、千の", "page": 2},
{"word": "ask", "meaning": "尋ねる", "page": 2},
{"word": "land", "meaning": "土地", "page": 2},
{"word": "planet", "meaning": "惑星", "page": 2},
{"word": "pond", "meaning": "池", "page": 2},
{"word": "nature", "meaning": "自然", "page": 2},
{"word": "pig", "meaning": "ブタ", "page": 2},
{"word": "rabbit", "meaning": "ウサギ", "page": 2},
{"word": "laugh", "meaning": "笑う", "page": 2},
{"word": "just", "meaning": "ちょうど", "page": 2},
{"word": "real", "meaning": "ほんとうの", "page": 2},
{"word": "stood", "meaning": "立った", "page": 2},
{"word": "while", "meaning": "～する間", "page": 2},
{"word": "fail", "meaning": "失敗する", "page": 2},
{"word": "put", "meaning": "置く", "page": 2},
{"word": "arm", "meaning": "腕", "page": 2},
{"word": "listen", "meaning": "聴く", "page": 2},
{"word": "enjoyed", "meaning": "楽しんだ", "page": 2},
{"word": "spoke", "meaning": "話した", "page": 2},
{"word": "save", "meaning": "節約する", "page": 2},
{"word": "tried", "meaning": "試した", "page": 2},
{"word": "still", "meaning": "まだ", "page": 2},
{"word": "sold", "meaning": "売った", "page": 2},
{"word": "foolish", "meaning": "愚かな", "page": 2},
{"word": "watched", "meaning": "見た", "page": 2},
{"word": "first", "meaning": "1番目", "page": 2},
{"word": "they", "meaning": "彼らは", "page": 2},
{"word": "played", "meaning": "演奏した", "page": 2},
{"word": "realize", "meaning": "実現する", "page": 2},
{"word": "important", "meaning": "重要な", "page": 2},
{"word": "forth", "meaning": "4番目", "page": 2},
{"word": "hers", "meaning": "彼女のもの", "page": 2},
{"word": "honest", "meaning": "正直な", "page": 2},
{"word": "between", "meaning": "～と～の間", "page": 3},
{"word": "took", "meaning": "取った", "page": 3},
{"word": "zoo", "meaning": "動物園", "page": 3},
{"word": "quiet", "meaning": "静かな", "page": 3},
{"word": "then", "meaning": "そのとき", "page": 3},
{"word": "when", "meaning": "～するとき", "page": 3},
{"word": "got", "meaning": "得えた", "page": 3},
{"word": "yours", "meaning": "あなたのもの", "page": 3},
{"word": "joy", "meaning": "喜び", "page": 3},
{"word": "weak", "meaning": "弱い", "page": 3},
{"word": "it", "meaning": "それは", "page": 3},
{"word": "thought", "meaning": "考え", "page": 3},
{"word": "use", "meaning": "使う", "page": 3},
{"word": "senior", "meaning": "年上の", "page": 3},
{"word": "waste", "meaning": "浪費", "page": 3},
{"word": "net", "meaning": "網", "page": 3},
{"word": "had", "meaning": "食べた", "page": 3},
{"word": "lose", "meaning": "失う", "page": 3},
{"word": "bought", "meaning": "買った", "page": 3},
{"word": "poor", "meaning": "貧乏な", "page": 3},
{"word": "rainy", "meaning": "雨降の", "page": 3},
{"word": "her", "meaning": "彼女の", "page": 3},
{"word": "its", "meaning": "その", "page": 3},
{"word": "weather", "meaning": "天気", "page": 3},
{"word": "wave", "meaning": "波", "page": 3},
{"word": "went", "meaning": "行った", "page": 3},
{"word": "but", "meaning": "しかし", "page": 3},
{"word": "her", "meaning": "彼女の", "page": 3},
{"word": "once", "meaning": "かつて", "page": 3},
{"word": "his", "meaning": "彼の", "page": 3},
{"word": "stay", "meaning": "滞在", "page": 3},
{"word": "you", "meaning": "あなたは", "page": 3},
{"word": "their", "meaning": "彼らの", "page": 3},
{"word": "your", "meaning": "あなたの", "page": 3},
{"word": "yesterday", "meaning": "昨日", "page": 3},
{"word": "east", "meaning": "東", "page": 3},
{"word": "she", "meaning": "彼女は", "page": 3},
{"word": "How", "meaning": "どのぐらい", "page": 3},
{"word": "please", "meaning": "喜ばせる", "page": 3},
{"word": "toy", "meaning": "玩具", "page": 3},
{"word": "used", "meaning": "使った", "page": 3},
{"word": "fat", "meaning": "太った", "page": 3},
{"word": "dislike", "meaning": "嫌う", "page": 3},
{"word": "it", "meaning": "それは", "page": 3},
{"word": "he", "meaning": "彼は", "page": 3},
{"word": "studied", "meaning": "勉強した", "page": 3},
{"word": "cloudy", "meaning": "曇った", "page": 3},
{"word": "worried", "meaning": "心配した", "page": 3},
{"word": "made", "meaning": "作った", "page": 3},
{"word": "guess", "meaning": "推測する", "page": 3},
{"word": "event", "meaning": "出来事", "page": 3},
{"word": "sweet", "meaning": "甘い", "page": 3},
{"word": "fruit", "meaning": "果物", "page": 3},
{"word": "fourteen", "meaning": "8", "page": 3},
{"word": "soup", "meaning": "スープ", "page": 3},
{"word": "science", "meaning": "科学", "page": 3},
{"word": "drink", "meaning": "飲む", "page": 3},
{"word": "station", "meaning": "駅", "page": 3},
{"word": "seventy", "meaning": "4", "page": 3},
{"word": "cake", "meaning": "ケーキ", "page": 3},
{"word": "stand", "meaning": "立つ", "page": 3},
{"word": "hope", "meaning": "望む", "page": 3},
{"word": "street", "meaning": "通り", "page": 3},
{"word": "friend", "meaning": "友達", "page": 3},
{"word": "rise", "meaning": "昇る", "page": 3},
{"word": "sometimes", "meaning": "時々", "page": 3},
{"word": "frog", "meaning": "カエル", "page": 3},
{"word": "supermarket", "meaning": "スーパー", "page": 3},
{"word": "small", "meaning": "小さい", "page": 3},
{"word": "summer", "meaning": "夏", "page": 3},
{"word": "stop", "meaning": "止める", "page": 3},
{"word": "subject", "meaning": "科目、題目", "page": 3},
{"word": "help", "meaning": "助ける", "page": 3},
{"word": "green", "meaning": "緑", "page": 3},
{"word": "here", "meaning": "ここに", "page": 3},
{"word": "garbage", "meaning": "ゴミ", "page": 3},
{"word": "by", "meaning": "のそばに、によって", "page": 3},
{"word": "sister", "meaning": "姉妹", "page": 3},
{"word": "good", "meaning": "良い", "page": 3},
{"word": "seven", "meaning": "1", "page": 3},
{"word": "family", "meaning": "家族", "page": 4},
{"word": "food", "meaning": "食べ物", "page": 4},
{"word": "hot", "meaning": "暑い", "page": 4},
{"word": "great", "meaning": "素晴らしい、広大な", "page": 4},
{"word": "hear", "meaning": "聞く", "page": 4},
{"word": "funny", "meaning": "可笑しい", "page": 4},
{"word": "festival", "meaning": "祭", "page": 4},
{"word": "straight", "meaning": "まっすぐに", "page": 4},
{"word": "telephone", "meaning": "電話", "page": 4},
{"word": "forty", "meaning": "40", "page": 4},
{"word": "sport", "meaning": "スポーツ", "page": 4},
{"word": "Do", "meaning": "する", "page": 4},
{"word": "go", "meaning": "行く", "page": 4},
{"word": "strong", "meaning": "強い", "page": 4},
{"word": "teacher", "meaning": "先生", "page": 4},
{"word": "head", "meaning": "頭", "page": 4},
{"word": "eighteen", "meaning": "6", "page": 4},
{"word": "culture", "meaning": "文化", "page": 4},
{"word": "second", "meaning": "2番目", "page": 4},
{"word": "homework", "meaning": "宿題", "page": 4},
{"word": "language", "meaning": "言語", "page": 4},
{"word": "swim", "meaning": "泳ぐ", "page": 4},
{"word": "fast", "meaning": "速い", "page": 4},
{"word": "six", "meaning": "6", "page": 4},
{"word": "school", "meaning": "学校", "page": 4},
{"word": "speak", "meaning": "話す", "page": 4},
{"word": "ship", "meaning": "船", "page": 4},
{"word": "ten", "meaning": "4", "page": 4},
{"word": "shopping", "meaning": "買い物", "page": 4},
{"word": "hospital", "meaning": "病院", "page": 4},
{"word": "sing", "meaning": "歌う", "page": 4},
{"word": "famous", "meaning": "有名な", "page": 4},
{"word": "fifty", "meaning": "50", "page": 4},
{"word": "shop", "meaning": "店", "page": 4},
{"word": "season", "meaning": "季節", "page": 4},
{"word": "delicious", "meaning": "美味しい", "page": 4},
{"word": "short", "meaning": "短い", "page": 4},
{"word": "everyone", "meaning": "みんな", "page": 4},
{"word": "star", "meaning": "星", "page": 4},
{"word": "soft", "meaning": "柔らかい", "page": 4},
{"word": "from", "meaning": "～から", "page": 4},
{"word": "happy", "meaning": "幸福な", "page": 4},
{"word": "buy", "meaning": "買う", "page": 4},
{"word": "Friday", "meaning": "金曜日", "page": 4},
{"word": "have", "meaning": "持っている", "page": 4},
{"word": "scientist", "meaning": "科学者", "page": 4},
{"word": "girl", "meaning": "少女", "page": 4},
{"word": "theirs", "meaning": "彼らのもの", "page": 4},
{"word": "favorite", "meaning": "お気に入りの", "page": 4},
{"word": "spell", "meaning": "を綴る", "page": 4},
{"word": "September", "meaning": "3月", "page": 4},
{"word": "Sunday", "meaning": "日曜日", "page": 4},
{"word": "beautiful", "meaning": "美しい", "page": 4},
{"word": "table", "meaning": "机", "page": 4},
{"word": "fifteen", "meaning": "9", "page": 4},
{"word": "desk", "meaning": "机", "page": 4},
{"word": "grape", "meaning": "ブドウ", "page": 4},
{"word": "for", "meaning": "のために", "page": 4},
{"word": "four", "meaning": "4", "page": 4},
{"word": "fun", "meaning": "楽しみ", "page": 4},
{"word": "house", "meaning": "家", "page": 4},
{"word": "temple", "meaning": "お寺", "page": 4},
{"word": "study", "meaning": "勉強する", "page": 4},
{"word": "hand", "meaning": "手", "page": 4},
{"word": "snowy", "meaning": "雪の降る", "page": 4},
{"word": "flower", "meaning": "花", "page": 4},
{"word": "August", "meaning": "2月", "page": 4},
{"word": "get", "meaning": "得る", "page": 4},
{"word": "subway", "meaning": "地下鉄", "page": 4},
{"word": "February", "meaning": "2月", "page": 4},
{"word": "walk", "meaning": "散歩", "page": 4},
{"word": "together", "meaning": "一緒に", "page": 4},
{"word": "umbrella", "meaning": "傘", "page": 4},
{"word": "the", "meaning": "その", "page": 4},
{"word": "with", "meaning": "と一緒に", "page": 4},
{"word": "thirteen", "meaning": "7", "page": 4},
{"word": "usually", "meaning": "普通は", "page": 4},
{"word": "who", "meaning": "だれ", "page": 4},
{"word": "very", "meaning": "非常に", "page": 4},
{"word": "My", "meaning": "私の", "page": 4},
{"word": "tiger", "meaning": "トラ", "page": 5},
{"word": "wall", "meaning": "壁", "page": 5},
{"word": "world", "meaning": "世界、地球", "page": 5},
{"word": "like", "meaning": "好む", "page": 5},
{"word": "travel", "meaning": "旅行", "page": 5},
{"word": "winter", "meaning": "冬", "page": 5},
{"word": "train", "meaning": "列車", "page": 5},
{"word": "under", "meaning": "下の", "page": 5},
{"word": "try", "meaning": "試す", "page": 5},
{"word": "was", "meaning": "でした", "page": 5},
{"word": "turn", "meaning": "曲がる、回る、変化する", "page": 5},
{"word": "two", "meaning": "2", "page": 5},
{"word": "up", "meaning": "上へ", "page": 5},
{"word": "twelve", "meaning": "6", "page": 5},
{"word": "window", "meaning": "窓", "page": 5},
{"word": "tree", "meaning": "木", "page": 5},
{"word": "visit", "meaning": "訪問する", "page": 5},
{"word": "three", "meaning": "3", "page": 5},
{"word": "Tuesday", "meaning": "火曜日", "page": 5},
{"word": "this", "meaning": "この", "page": 5},
{"word": "tower", "meaning": "塔", "page": 5},
{"word": "third", "meaning": "3番目", "page": 5},
{"word": "write", "meaning": "書く、手紙を書く", "page": 5},
{"word": "Wednesday", "meaning": "水曜日", "page": 5},
{"word": "town", "meaning": "街", "page": 5},
{"word": "twenty", "meaning": "20", "page": 5},
{"word": "thirty", "meaning": "30", "page": 5},
{"word": "to", "meaning": "～へ", "page": 5},
{"word": "trip", "meaning": "旅行", "page": 5},
{"word": "where", "meaning": "どこに", "page": 5},
{"word": "want", "meaning": "欲しい", "page": 5},
{"word": "welcome", "meaning": "歓迎する", "page": 5},
{"word": "white", "meaning": "白", "page": 5},
{"word": "wonderful", "meaning": "すばらしい", "page": 5},
{"word": "why", "meaning": "なぜ", "page": 5},
{"word": "year", "meaning": "年", "page": 5},
{"word": "yellow", "meaning": "黄色", "page": 5},
{"word": "low", "meaning": "低い", "page": 5},
{"word": "grow", "meaning": "育てる", "page": 5},
{"word": "history", "meaning": "歴史", "page": 5},
{"word": "wash", "meaning": "洗う", "page": 5},
{"word": "many", "meaning": "多くの", "page": 5},
{"word": "beer", "meaning": "ビール", "page": 5},
{"word": "doctor", "meaning": "医者", "page": 5},
{"word": "large", "meaning": "大きい、広い", "page": 5},
{"word": "begin", "meaning": "始まる", "page": 5},
{"word": "bridge", "meaning": "橋", "page": 5},
{"word": "December", "meaning": "6月", "page": 5},
{"word": "enjoy", "meaning": "楽しむ", "page": 5},
{"word": "all", "meaning": "全部、全員、全て、みな", "page": 5},
{"word": "eight", "meaning": "2", "page": 5},
{"word": "or", "meaning": "それとも", "page": 5},
{"word": "nine", "meaning": "3", "page": 5},
{"word": "elementary school", "meaning": "小学校", "page": 5},
{"word": "absent", "meaning": "欠席の", "page": 5},
{"word": "am", "meaning": "いる、ある", "page": 5},
{"word": "not", "meaning": "～でない", "page": 5},
{"word": "room", "meaning": "部屋", "page": 5},
{"word": "if", "meaning": "もし～なら", "page": 5},
{"word": "airplane", "meaning": "飛行機", "page": 5},
{"word": "on", "meaning": "の上に", "page": 5},
{"word": "climb", "meaning": "登る", "page": 5},
{"word": "sad", "meaning": "悲しい", "page": 5},
{"word": "stopped", "meaning": "止まった", "page": 5},
{"word": "a few", "meaning": "いくらかの", "page": 5},
{"word": "be scared of", "meaning": "が怖い", "page": 5},
{"word": "arrive at", "meaning": "に到着する", "page": 5},
{"word": "and so on", "meaning": "などなど", "page": 5},
{"word": "January", "meaning": "1月", "page": 5},
{"word": "at noon", "meaning": "正午に", "page": 5},
{"word": "ask about", "meaning": "～について聞く", "page": 5},
{"word": "drum", "meaning": "太鼓", "page": 5},
{"word": "Japan", "meaning": "日本", "page": 5},
{"word": "meet", "meaning": "会う", "page": 5},
{"word": "talk to", "meaning": "に話しかける", "page": 5},
{"word": "for example", "meaning": "例えば", "page": 5},
{"word": "reading", "meaning": "読書", "page": 5},
{"word": "elementary school", "meaning": "小学校", "page": 5},
{"word": "car", "meaning": "自動車", "page": 5},
{"word": "clothes", "meaning": "服", "page": 5},
{"word": "evening", "meaning": "夕方", "page": 5},
{"word": "way", "meaning": "道、方法", "page": 6},
{"word": "host", "meaning": "主人", "page": 6},
{"word": "say again", "meaning": "もう一度言う", "page": 6},
{"word": "hat", "meaning": "帽子", "page": 6},
{"word": "most of", "meaning": "のほとんど", "page": 6},
{"word": "can", "meaning": "～できる", "page": 6},
{"word": "number", "meaning": "数", "page": 6},
{"word": "nest", "meaning": "巣", "page": 6},
{"word": "listen to", "meaning": "聴く", "page": 6},
{"word": "bear", "meaning": "クマ", "page": 6},
{"word": "go abroad", "meaning": "外国に行く", "page": 6},
{"word": "and", "meaning": "～と", "page": 6},
{"word": "job", "meaning": "仕事", "page": 6},
{"word": "November", "meaning": "5月", "page": 6},
{"word": "become", "meaning": "～になる", "page": 6},
{"word": "look", "meaning": "見る", "page": 6},
{"word": "country", "meaning": "国", "page": 6},
{"word": "cow", "meaning": "ウシ", "page": 6},
{"word": "bookstore", "meaning": "本屋", "page": 6},
{"word": "dinner", "meaning": "夕食", "page": 6},
{"word": "afternoon", "meaning": "午後", "page": 6},
{"word": "March", "meaning": "3月", "page": 6},
{"word": "dream", "meaning": "夢", "page": 6},
{"word": "take out", "meaning": "持ち帰り", "page": 6},
{"word": "snake", "meaning": "蛇", "page": 6},
{"word": "gave", "meaning": "与えた", "page": 6},
{"word": "show around", "meaning": "に見せて回る", "page": 6},
{"word": "bag", "meaning": "カバン", "page": 6},
{"word": "ninety", "meaning": "30", "page": 6},
{"word": "fine", "meaning": "元気な、晴れた", "page": 6},
{"word": "add", "meaning": "加える", "page": 6},
{"word": "down", "meaning": "下に", "page": 6},
{"word": "make own bed", "meaning": "ベッドを整える", "page": 6},
{"word": "leave", "meaning": "去る、残す、置いて行く", "page": 6},
{"word": "one day", "meaning": "ある日", "page": 6},
{"word": "brother", "meaning": "兄弟", "page": 6},
{"word": "again", "meaning": "もう一度、再び、また", "page": 6},
{"word": "best", "meaning": "一番良い", "page": 6},
{"word": "walk to", "meaning": "へ歩いて行く", "page": 6},
{"word": "sat", "meaning": "座った", "page": 6},
{"word": "worry about", "meaning": "について心配する", "page": 6},
{"word": "ask for", "meaning": "～に求める", "page": 6},
{"word": "let's", "meaning": "さあ～しよう", "page": 6},
{"word": "bird", "meaning": "鳥", "page": 6},
{"word": "purple", "meaning": "紫色", "page": 6},
{"word": "medicine", "meaning": "薬", "page": 6},
{"word": "clever", "meaning": "利口な", "page": 6},
{"word": "eighty", "meaning": "20", "page": 6},
{"word": "big", "meaning": "大きい", "page": 6},
{"word": "sheep", "meaning": "ヒツジ", "page": 6},
{"word": "look at", "meaning": "を見る", "page": 6},
{"word": "field trip", "meaning": "遠足", "page": 6},
{"word": "airport", "meaning": "空港", "page": 6},
{"word": "play", "meaning": "劇", "page": 6},
{"word": "cold", "meaning": "冷たい", "page": 6},
{"word": "join", "meaning": "参加する", "page": 6},
{"word": "though", "meaning": "～だけれど", "page": 6},
{"word": "hurry", "meaning": "急ぐ", "page": 6},
{"word": "borrow", "meaning": "借りる", "page": 6},
{"word": "that", "meaning": "あれ", "page": 6},
{"word": "ever", "meaning": "今まで", "page": 6},
{"word": "from the experience", "meaning": "経験から", "page": 6},
{"word": "meaning", "meaning": "意味", "page": 6},
{"word": "hard", "meaning": "一生懸命に", "page": 6},
{"word": "problem", "meaning": "問題", "page": 6},
{"word": "baseball", "meaning": "野球", "page": 6},
{"word": "seventeen", "meaning": "5", "page": 6},
{"word": "about", "meaning": "について、に関する", "page": 6},
{"word": "by bus", "meaning": "バスで", "page": 6},
{"word": "happiness", "meaning": "幸福", "page": 6},
{"word": "call back", "meaning": "折り返し電話する", "page": 6},
{"word": "think of", "meaning": "思い付く", "page": 6},
{"word": "south", "meaning": "南", "page": 6},
{"word": "did", "meaning": "した", "page": 6},
{"word": "after", "meaning": "～の後で", "page": 6},
{"word": "eat", "meaning": "食べる", "page": 6},
{"word": "blue", "meaning": "青い", "page": 6},
{"word": "black", "meaning": "黒い", "page": 6},
{"word": "easy", "meaning": "簡単な", "page": 6},
{"word": "look after", "meaning": "の面倒を見る", "page": 7},
{"word": "practice", "meaning": "練習する", "page": 7},
{"word": "fool", "meaning": "馬鹿", "page": 7},
{"word": "decide to", "meaning": "に決める", "page": 7},
{"word": "farewell party", "meaning": "送別会", "page": 7},
{"word": "player", "meaning": "選手", "page": 7},
{"word": "Japanese", "meaning": "日本人", "page": 7},
{"word": "afraid", "meaning": "恐れて", "page": 7},
{"word": "bread", "meaning": "パン", "page": 7},
{"word": "Thursday", "meaning": "木曜日", "page": 7},
{"word": "sixteen", "meaning": "10", "page": 7},
{"word": "chair", "meaning": "椅子", "page": 7},
{"word": "park", "meaning": "公園", "page": 7},
{"word": "cat", "meaning": "猫", "page": 7},
{"word": "picture", "meaning": "絵、写真", "page": 7},
{"word": "him", "meaning": "彼を(に)", "page": 7},
{"word": "light", "meaning": "光", "page": 7},
{"word": "July", "meaning": "1月", "page": 7},
{"word": "sleep", "meaning": "眠る", "page": 7},
{"word": "know", "meaning": "知っている", "page": 7},
{"word": "dish", "meaning": "皿", "page": 7},
{"word": "too ～ for", "meaning": "～すぎる", "page": 7},
{"word": "poem", "meaning": "詩", "page": 7},
{"word": "sit down", "meaning": "座る", "page": 7},
{"word": "kind to", "meaning": "に対して親切な", "page": 7},
{"word": "nurse", "meaning": "看護師", "page": 7},
{"word": "box", "meaning": "箱", "page": 7},
{"word": "neck", "meaning": "首", "page": 7},
{"word": "ate", "meaning": "食べた", "page": 7},
{"word": "take care of", "meaning": "の面倒を見る", "page": 7},
{"word": "every minutes", "meaning": "毎分ごとに", "page": 7},
{"word": "work for", "meaning": "のために働く", "page": 7},
{"word": "another", "meaning": "もう一つの", "page": 7},
{"word": "live in", "meaning": "に住む", "page": 7},
{"word": "ear", "meaning": "耳", "page": 7},
{"word": "get up", "meaning": "起きる", "page": 7},
{"word": "me", "meaning": "私を(に)", "page": 7},
{"word": "mouth", "meaning": "口", "page": 7},
{"word": "die", "meaning": "死ぬ", "page": 7},
{"word": "May", "meaning": "5月", "page": 7},
{"word": "difficult", "meaning": "難しい", "page": 7},
{"word": "nineteen", "meaning": "7", "page": 7},
{"word": "body", "meaning": "身体", "page": 7},
{"word": "during", "meaning": "～の間", "page": 7},
{"word": "new", "meaning": "新しい", "page": 7},
{"word": "musician", "meaning": "音楽家", "page": 7},
{"word": "egg", "meaning": "卵", "page": 7},
{"word": "lend", "meaning": "貸す", "page": 7},
{"word": "monkey", "meaning": "サル", "page": 7},
{"word": "take a rest", "meaning": "休憩する", "page": 7},
{"word": "math", "meaning": "数学", "page": 7},
{"word": "clock", "meaning": "置き時計", "page": 7},
{"word": "queen", "meaning": "女王", "page": 7},
{"word": "boy", "meaning": "少年", "page": 7},
{"word": "Let us(Let's)", "meaning": "～しましょう", "page": 7},
{"word": "capital", "meaning": "首都", "page": 7},
{"word": "in", "meaning": "の中に", "page": 7},
{"word": "on weekends", "meaning": "週末に", "page": 7},
{"word": "million", "meaning": "40万", "page": 7},
{"word": "name", "meaning": "名前", "page": 7},
{"word": "away", "meaning": "離れて", "page": 7},
{"word": "brought", "meaning": "持って来た", "page": 7},
{"word": "lived", "meaning": "住んだ", "page": 7},
{"word": "map", "meaning": "地図", "page": 7},
{"word": "our", "meaning": "私たちの", "page": 7},
{"word": "cook", "meaning": "料理する", "page": 7},
{"word": "try on", "meaning": "試着する", "page": 7},
{"word": "strange", "meaning": "奇妙な", "page": 7},
{"word": "grandfather", "meaning": "祖父", "page": 7},
{"word": "someone in need", "meaning": "助けが必要な人", "page": 7},
{"word": "be", "meaning": "である", "page": 7},
{"word": "stay up", "meaning": "起きている", "page": 7},
{"word": "to go", "meaning": "持ち帰り", "page": 7},
{"word": "autumn", "meaning": "秋", "page": 7},
{"word": "birthday", "meaning": "誕生日", "page": 7},
{"word": "classmate", "meaning": "同級生", "page": 7},
{"word": "night", "meaning": "夜", "page": 7},
{"word": "hall", "meaning": "廊下", "page": 7},
{"word": "change", "meaning": "変わる", "page": 7},
{"word": "bath", "meaning": "風呂", "page": 7},
{"word": "beach", "meaning": "砂浜", "page": 8},
{"word": "write down", "meaning": "書く", "page": 8},
{"word": "clean", "meaning": "きれいな", "page": 8},
{"word": "be(get) excited", "meaning": "興奮をする", "page": 8},
{"word": "knee", "meaning": "ひざ", "page": 8},
{"word": "sixty", "meaning": "60", "page": 8},
{"word": "magazine", "meaning": "雑誌", "page": 8},
{"word": "much", "meaning": "たくさん", "page": 8},
{"word": "English", "meaning": "英語", "page": 8},
{"word": "time", "meaning": "時、～回", "page": 8},
{"word": "choose", "meaning": "選ぶ", "page": 8},
{"word": "talk about", "meaning": "について話す", "page": 8},
{"word": "by car", "meaning": "車まで", "page": 8},
{"word": "get along with", "meaning": "うまくやる", "page": 8},
{"word": "discover", "meaning": "発見する", "page": 8},
{"word": "brush", "meaning": "を磨く", "page": 8},
{"word": "day", "meaning": "日", "page": 8},
{"word": "nose", "meaning": "鼻", "page": 8},
{"word": "bike", "meaning": "自転車", "page": 8},
{"word": "farm", "meaning": "農場", "page": 8},
{"word": "one", "meaning": "1", "page": 8},
{"word": "old", "meaning": "古い", "page": 8},
{"word": "cap", "meaning": "帽子", "page": 8},
{"word": "police", "meaning": "警察", "page": 8},
{"word": "explain", "meaning": "説明する", "page": 8},
{"word": "luck", "meaning": "運", "page": 8},
{"word": "read", "meaning": "読む", "page": 8},
{"word": "grass", "meaning": "草", "page": 8},
{"word": "north", "meaning": "北", "page": 8},
{"word": "date", "meaning": "日付", "page": 8},
{"word": "learn about", "meaning": "について学ぶ", "page": 8},
{"word": "have a headache", "meaning": "頭痛がする", "page": 8},
{"word": "always", "meaning": "いつも", "page": 8},
{"word": "run", "meaning": "走る", "page": 8},
{"word": "saw", "meaning": "見た", "page": 8},
{"word": "earth", "meaning": "地球", "page": 8},
{"word": "cute", "meaning": "可愛い", "page": 8},
{"word": "stand up", "meaning": "立つ", "page": 8},
{"word": "book", "meaning": "本", "page": 8},
{"word": "place", "meaning": "場所", "page": 8},
{"word": "dry", "meaning": "乾いた", "page": 8},
{"word": "for here", "meaning": "ここで食べる", "page": 8},
{"word": "came", "meaning": "来た", "page": 8},
{"word": "search for", "meaning": "を探索する", "page": 8},
{"word": "color", "meaning": "色", "page": 8},
{"word": "on your right", "meaning": "右側に", "page": 8},
{"word": "try to", "meaning": "しようとする", "page": 8},
{"word": "classroom", "meaning": "教室", "page": 8},
{"word": "advice", "meaning": "忠告", "page": 8},
{"word": "Monday", "meaning": "月曜日", "page": 8},
{"word": "row", "meaning": "こぐ", "page": 8},
{"word": "excuse", "meaning": "許す", "page": 8},
{"word": "them", "meaning": "彼らを(に)", "page": 8},
{"word": "leave for", "meaning": "へ出かける", "page": 8},
{"word": "newspaper", "meaning": "新聞", "page": 8},
{"word": "ruler", "meaning": "定規", "page": 8},
{"word": "introduce", "meaning": "紹介する", "page": 8},
{"word": "really", "meaning": "本当に", "page": 8},
{"word": "keep in touch", "meaning": "連絡を取り合う", "page": 8},
{"word": "understood", "meaning": "理解した", "page": 8},
{"word": "April", "meaning": "4月", "page": 8},
{"word": "chicken", "meaning": "鶏肉", "page": 8},
{"word": "bring", "meaning": "持って来る", "page": 8},
{"word": "go to", "meaning": "へ行く", "page": 8},
{"word": "believe", "meaning": "信じる", "page": 8},
{"word": "spring", "meaning": "春", "page": 8},
{"word": "child", "meaning": "子供", "page": 8},
{"word": "on the way", "meaning": "道の途中で", "page": 8},
{"word": "in the future", "meaning": "将来に", "page": 8},
{"word": "month", "meaning": "月", "page": 8},
{"word": "salad", "meaning": "サラダ", "page": 8},
{"word": "is", "meaning": "ある、いる", "page": 8},
{"word": "beef", "meaning": "牛肉", "page": 8},
{"word": "happen", "meaning": "起こる", "page": 8},
{"word": "take it back", "meaning": "取り戻す", "page": 8},
{"word": "stationery shop", "meaning": "文房具店", "page": 8},
{"word": "pencil", "meaning": "鉛筆", "page": 8},
{"word": "sang", "meaning": "歌った", "page": 8},
{"word": "over there", "meaning": "あそこに", "page": 8},
{"word": "mine", "meaning": "私のもの", "page": 8},
{"word": "entrance ceremony", "meaning": "入学式", "page": 8},
{"word": "horse", "meaning": "馬", "page": 8},
{"word": "wait for", "meaning": "を待つ", "page": 8},
{"word": "busy", "meaning": "忙しい", "page": 8},
{"word": "junior high school", "meaning": "中学校", "page": 9},
{"word": "lie", "meaning": "嘘", "page": 9},
{"word": "library", "meaning": "図書館", "page": 9},
{"word": "foreign language", "meaning": "外国語", "page": 9},
{"word": "sorry", "meaning": "ごめんなさい", "page": 9},
{"word": "bicycle", "meaning": "自転車", "page": 9},
{"word": "cool", "meaning": "かっこいい", "page": 9},
{"word": "dog", "meaning": "イヌ", "page": 9},
{"word": "on the wall", "meaning": "壁に", "page": 9},
{"word": "stand by", "meaning": "そばに立つ", "page": 9},
{"word": "eleven", "meaning": "5", "page": 9},
{"word": "June", "meaning": "6月", "page": 9},
{"word": "because", "meaning": "なぜなら", "page": 9},
{"word": "jump", "meaning": "跳ぶ", "page": 9},
{"word": "carefully", "meaning": "注意深く", "page": 9},
{"word": "memory", "meaning": "記憶", "page": 9},
{"word": "college", "meaning": "大学", "page": 9},
{"word": "be born", "meaning": "生まれる", "page": 9},
{"word": "even", "meaning": "～さえ", "page": 9},
{"word": "carry", "meaning": "運ぶ", "page": 9},
{"word": "out", "meaning": "外に", "page": 9},
{"word": "exam", "meaning": "試験", "page": 9},
{"word": "Saturday", "meaning": "土曜日", "page": 9},
{"word": "learn a lot from", "meaning": "からたくさん学ぶ", "page": 9},
{"word": "October", "meaning": "4月", "page": 9},
{"word": "hungry", "meaning": "空腹の", "page": 9},
{"word": "at", "meaning": "で、に", "page": 9},
{"word": "with a smile", "meaning": "笑顔で", "page": 9},
{"word": "dictionary", "meaning": "辞書", "page": 9},
{"word": "lunch", "meaning": "昼食", "page": 9},
{"word": "museum", "meaning": "博物館", "page": 9},
{"word": "red", "meaning": "赤い", "page": 9},
{"word": "between A and B", "meaning": "AとBの間", "page": 9},
{"word": "school festival", "meaning": "文化祭", "page": 9},
{"word": "life", "meaning": "生活", "page": 9},
{"word": "bright", "meaning": "明るい", "page": 9},
{"word": "breakfast", "meaning": "朝食", "page": 9},
{"word": "make", "meaning": "作る、～を～にする", "page": 9},
{"word": "morning", "meaning": "朝", "page": 9},
{"word": "long", "meaning": "長い", "page": 9},
{"word": "drama", "meaning": "劇", "page": 9},
{"word": "high school", "meaning": "高校", "page": 9},
{"word": "sunny", "meaning": "晴れた", "page": 9},
{"word": "go straight", "meaning": "まっすぐ行く", "page": 9},
{"word": "too", "meaning": "～もまた", "page": 9},
{"word": "brown", "meaning": "茶色の", "page": 9},
{"word": "nice", "meaning": "良い", "page": 9},
{"word": "cup", "meaning": "カップ", "page": 9},
{"word": "we", "meaning": "私たちは", "page": 9},
{"word": "cried", "meaning": "泣いた", "page": 9},
{"word": "never", "meaning": "1度もない", "page": 9},
{"word": "How about", "meaning": "はどうですか？", "page": 9},
{"word": "law", "meaning": "法律", "page": 9},
{"word": "ride", "meaning": "乗る", "page": 9},
{"word": "example", "meaning": "例", "page": 9},
{"word": "find", "meaning": "見つける", "page": 9},
{"word": "left", "meaning": "左", "page": 9},
{"word": "eraser", "meaning": "消しゴム", "page": 9},
{"word": "bean", "meaning": "豆", "page": 9},
{"word": "plan", "meaning": "計画する", "page": 9},
{"word": "apple", "meaning": "リンゴ", "page": 9},
{"word": "eye", "meaning": "目", "page": 9},
{"word": "mother", "meaning": "母", "page": 9},
{"word": "sent", "meaning": "送った", "page": 9},
{"word": "mouse", "meaning": "ネズミ", "page": 9},
{"word": "go back to", "meaning": "に戻る", "page": 9},
{"word": "feel", "meaning": "感じる", "page": 9},
{"word": "help with", "meaning": "を助ける", "page": 9},
{"word": "city", "meaning": "市", "page": 9},
{"word": "even so", "meaning": "それでも", "page": 9},
{"word": "on your left", "meaning": "左側に", "page": 9},
{"word": "try hard", "meaning": "一生懸命する", "page": 10},
{"word": "live abroad", "meaning": "海外で生活する", "page": 10},
{"word": "from now on", "meaning": "これから", "page": 10},
{"word": "get tired", "meaning": "疲れる", "page": 10},
{"word": "check ～ out", "meaning": "を確認する", "page": 10},
{"word": "be interested in", "meaning": "に興味がある", "page": 10},
{"word": "from ～ to ～", "meaning": "～から～まで", "page": 10},
{"word": "be famous for", "meaning": "で有名である", "page": 10},
{"word": "try on", "meaning": "試着する", "page": 10},
{"word": "try to", "meaning": "試す", "page": 10},
{"word": "work for", "meaning": "のために働く", "page": 10}
];
const level3Words = [
];
const level2_lowWords = [
];
const level2_low2Words = [
];
const level2Words = [
];
const level1_lowWords = [
];
const level1Words = [
];
